- Gopkg.lock
- core/node.go
- core/node_test.go
- demo/add_order/main.go
- demo/add_peer/main.go
- main.go
- ws/client.go
- ws/client_server_test.go
- ws/rpc_service.go
- ws/server.go
- Add `Connect` method to `core.Node` which is a thin wrapper around `host.Connect`.
- Add `AddPeer` RPC method for both server and client.
- Implement the new `AddPeer` method for `RPCHandler` in __main.go__.
- Split __demo/client__ into __demo/add_order__ and __demo/add_peer__.
This is really only for demo/testing purposes. We might remove the `AddPeer` RPC method after we implement peer discovery.
> Add the ability to add new peers over RPC

- constants/constants.go
- demo/add_order/main.go
- ethereum/sign.go
- ethereum/sign_test.go
- meshdb/meshdb_test.go
- ws/client_server_test.go
- zeroex/order.go
- zeroex/order_test.go
- zeroex/order_validator_test.go
This PR:
- Implements utility for signing a message via `eth_sign` and associated tests
- Add convenience method for signing a 0x order and returning the signature in the format expected by the smart contracts.
> ethereum/zeroex: Implement signing utilities

- Gopkg.lock
- Gopkg.toml
- blockwatch/watcher.go
- core/node.go
- core/node_test.go
- core/notifee.go
- main.go
This PR adds support for peer discovery via [go-libp2p-kad-dht](https://github.com/libp2p/go-libp2p-kad-dht) and [go-libp2p-discovery](https://github.com/libp2p/go-libp2p-discovery). It also adds a new environment variable `USE_BOOTSTRAP_LIST`. If set to "true", it uses the IPFS default bootstrap list to bootstrap the DHT.
WIP right now because of some weird behavior when using the bootstrap list. If you set it to "false", you can test peer discovery by following these steps:
1. Create three 0x Mesh nodes (A, B, and C).
2. Manually connect A to B via the `AddPeer` RPC method.
3. Manually connect B to C via the `AddPeer` RPC method.
4. Observe that A is introduced to C through B and they will connect to each other.
> Implement peer discovery

- .circleci/config.yml
- demo/add_order/main.go
- ethereum/eth_watcher_test.go
- ethereum/sign_test.go
- ethereum/wrappers/order_validator.go
- ethereum/wrappers/order_validator_aliases.go
- zeroex/order.go
- zeroex/order_test.go
- zeroex/order_validator.go
- zeroex/order_validator_test.go
This PR:
- Updates the Ganache snapshot we use to a version that includes a modified OrderValidator.sol contract with 0x signature validation added to `getOrderInfo()` and `getOrdersAndTradersInfo()` (which is the one we use to do batch order validation).
- Re-generates the OrderValidator contract wrapper to correspond to the updated contract.
- Refactors `BatchValidate` to call the new method, supplying the order signatures and checking the return value for invalid signatures.
- Adds a `BatchValidate` test to make sure it properly reports orders with invalid signatures.
> zeroex: Add order signature validation to `BatchValidate`

- Makefile
IMO the tests are getting too noisy and it is sometimes difficult to understand what went wrong when a test fails. When I was originally experimenting with adding the Wasm tests, it was helpful to use the `-v` flag to make sure all the tests were running as intended. At this point, I don't think it's necessary.
> Remove verbose flag when running tests

- db/query.go
- db/query_test.go
The bug was causing queries constructed with ValueFilter to also return any model where the target value was a prefix of the index value. So e.g., a query using `ValueFilter("foo")` would return models with a value of "foobar".
> Fix bug in db.Index.ValueFilter

- db/query.go
- db/query_test.go
This feature is going to be necessary in order to tackle #73.
> Add support for a new Query.Count method

- cmd/demo/add_order/main.go
- cmd/mesh/rpc_handler.go
- core/core.go
- rpc/client.go
- rpc/client_server_test.go
- rpc/service.go
- rpc/types.go
- zeroex/order_validator.go
Completes: https://github.com/0xProject/0x-mesh/issues/88
Since the caller now submits multiple orders in a single call, this method's return value is of type:
```
type AddOrdersResponse struct {
Added       []*zeroex.SuccinctOrderInfo
Invalid     []*zeroex.SuccinctOrderInfo
FailedToAdd []common.Hash
}
```
Why? 
- `Added`: Some orders pass the order validation test and are added to Mesh.
- `Invalid`: Some order are not added to Mesh because they fail the order validation test. By letting the client know, they can also drop those orders from their data store.
- `Failed`: Some orders are not added to Mesh if the network request to validate them fails unexpectedly. By letting the client know, they can then try and add those orders again in a new request.
> rpc: Refactor `AddOrder` to `AddOrders`

- zeroex/orderwatch/watcher.go
Copied TODO comment from code:
"With the current way the OrderWatcher is written, it is possible for multiple events to trigger logic that updates the orders in the DB simultaneously. This is mostly benign but is a waste of computation, and causes processes to try and delete orders the have already been deleted. In order to fix this, we need to re-write the event handling logic to queue the processing of events so that they happen sequentially rather then in parallel."
> orderwatch: Don't panic if attempt to delete already removed order

- db/escape.go
- ethereum/eth_watcher.go
- zeroex/order_validator.go
- zeroex/orderwatch/watcher.go
This PR edits the logs emitted on `GetOrdersAndTradersInfo()` request failures since it was too noisy and of limited use. Most of the time the failure has nothing to do with the orders submitted and more to do with other network disruptions.
> zeroex: Make `GetOrdersAndTradersInfo()` network request failure logs less noisy

- zeroex/orderwatch/watcher.go
When an expired order is discovered by the ExpirationWatcher it is immediately removed from it in order to continue validating other orders. The `unwatchOrder()` method in OrderWatcher was blindly telling the ExpirationWatcher to remove all orders, even those that should be unwatched because they have expired. This PR fixes the issue by discerning between `unwatch` requests because of expiry or other.
> orderwatch: Avoid attempting to remove orders from ExpirationWatcher multiple times

- zeroex/order.go
- zeroex/order_validator.go
- zeroex/order_validator_test.go
- zeroex/orderwatch/expirationwatch.go
This PR completes: https://github.com/0xProject/0x-mesh/issues/85 and https://github.com/0xProject/0x-mesh/issues/57https://github.com/0xProject/0x-mesh/issues/57
- Previously we were relying entirely on on-chain 0x order validation. Not only was this inefficient, the very call to the contract would fail if the supplied orders with incorrectly formatted. This PR thus adds the following off-chain validation checks:
- Make sure maker & taker assetData are decodable and supported
- Make sure signature is properly formatted and supported
- Make sure order isn't expired
- Make sure maker & taker assetAmounts are not 0
If any of these checks fail, `BatchFill()` won't include these orders in the contract call. An `OrderInfo` object for these invalid orders is still returned from `BatchFill()` …
> zeroex: Perform all possible off-chain 0x validation before on-chain validation

- db/query.go
- db/query_test.go
`Query.Offset` is an analog to the [`OFFSET` keyword in SQL](https://www.postgresql.org/docs/current/queries-limit.html). (Just as `Query.Max` is the analog to `LIMIT` in SQL).
This feature is important for addressing https://github.com/0xProject/0x-mesh/issues/84 and will likely be useful for future optimizations as well.
> Implement Query.Offset method

- zeroex/order.go
- zeroex/order_validator_test.go
Fixes #105. This also allows us to remove some lines of code in __zeroex/order_validator_test.go__.
> Make SignedOrder.Order not a pointer

- cmd/demo/add_order/main.go
- cmd/demo/subscribe_to_orders/main.go
It is useful to have a test script that continuously receives order events via subscription instead of just receiving one event. To accomplish this, I created a new script at __cmd/demo/subscribe_to_orders/main.go__. I also removed the subscription-related code from __cmd/demo/add_order/main.go__.
> Split order event subscription into separate demo script

- Gopkg.lock
- p2p/node.go
- p2p/node_test.go
- p2p/notifee.go
This PR changes our our main mechanism for communicating orders to peers from FloodSub to GossipSub. GossipSub is still not perfect for our use case, but it will dramatically reduce thrashing that can occur in FloodSub whenever new messages are sent to all peers. It should lead to more efficient bandwidth usage overall.
The change itself was really easy, but because GossipSub incurs higher latency, I had to make significant changes to our tests in order to get them working again.
> Use GossipSub instead of FloodSub

- zeroex/order.go
- zeroex/order_validator.go
These keys are sent over JSON-RPC to clients and their keys should be lower-case when sent.
> zeroex: Convert all struct keys to lower-case when output as JSON

- .circleci/config.yml
- Gopkg.lock
- Gopkg.toml
Fixes: #112
This PR supercedes #127 now that we've found an approach that doesn't require the removal of local signer.
The fix involved updating our `go-ethereum` dependency to include the commit that fixed their `CGO_ENABLED=0` flag. The new changes brought in also changed the code in `signer/core` so I had to make new changes in that package to re-enable WASM compilation (https://github.com/0xProject/go-ethereum/pull/5).
Mesh can now be compiled without cgo by running:
```
CGO_ENABLED=0 go build  -tags kqueue ./cmd/mesh
```
Note: the kqueue tags as per: https://github.com/rjeczalik/notify/issues/108
> Fix Mesh compilation without CGO & WASM compilation

- core/core.go
- core/encoding.go
- core/message_handler.go
- core/peer_score.go
- core/validation.go
- core/validators.go
- p2p/message.go
- p2p/node.go
- p2p/node_test.go
We've always wanted to perform ETH balance checks to limit the capacity for malicious actors to flood the network. The original plan was to calculate `(ETH balance of maker) / (total bytes of storage allocated to maker)`. However, we've discovered that it is almost impossible to determine the number of bytes of storage used by a given maker due to the fact that LevelDB uses opaque compression techniques. Even if we could do it, it would likely be computationally expensive and likely require iterating over a large number of keys.
As a compromise, we've chosen to use a less precise calculation: `(ETH balance of maker) / (total number of orders stored for that maker)`. Since orders can be theoretically unlimited in size, we've also decided to also add a max size for order messages. This PR …
> Implement a max message size for orders

- db/collection.go
- db/interfaces.go
- db/query.go
- db/snapshot.go
- db/snapshot_test.go
This is a prerequisite for https://github.com/0xProject/0x-mesh/issues/86. Without the ability to take a snapshot, we can't guarantee a consistent view of the current set of orders for RPC clients.
For the implementation, I first recognized that there are some common methods between [`leveldb.Snapshot`](https://godoc.org/github.com/syndtr/goleveldb/leveldb#Snapshot) and [`leveldb.DB`](https://godoc.org/github.com/syndtr/goleveldb/leveldb#DB). Specifically, the `Get`, `Has`, and `NewIterator` methods. These are the methods that we rely on throughout the codebase (e.g. for creating and running queries). I encapsulated the common functionality in an interface called `dbReader`, and we now use `dbReader` instead of `*db.DB` wherever possible. This abstraction allows us to use the same …
> db: Add support for snapshots

- Dockerfile
This PR adds a multi-stage `Dockerfile` that builds mesh without CGO.
The end alpine image contains only the statically linked binary -> no dependency on `musl` / `glibc`.
Supersedes https://github.com/0xProject/0x-mesh/pull/128 - removed the change to Makefile, and this PR is against master.
> Add multi-stage Dockerfile

- Dockerfile
Fixes: #138 
This PR makes the `Dockerfile` compile `mesh` with `CGO` enabled (and musl instead of glibc)
> compiles mesh with cgo (musl)

- .gitignore
- Gopkg.lock
- Makefile
- README.md
- cmd/mesh-keygen/main.go
- core/core.go
- p2p/node.go
- p2p/node_test.go
Fixes #130.
I also added a new command-line tool called `mesh-keygen` for generating key files in the appropriate format.
> Add support for persistent identities via a private key file

- db/collection.go
- db/index.go
- db/query.go
- db/snapshot.go
- db/snapshot_test.go
I discovered a bug in the snapshot feature introduced in #132. The tests were not sufficient to catch the bug, so this PR also improves the snapshot tests.
WIP because there is still an issue where `Delete` is not correctly isolated. When you call `Delete` after a snapshot is taken, the model also appears to be deleted in the snapshot.
> Fix bug where snapshot was not correctly isolated

- cmd/mesh/rpc_handler.go
Fixes: #109 
This PR:
- Adds logging of the err returned on rpcSub.Err() 
- Special-cases logging the expected `broken pipe` errors after a client disconnects as `trace` instead of the usual `error` severity. The `TODO` comment also documents this known race condition.
> rpc: Address `broken pipe` log spam

- db/batch.go
- db/col_info.go
- db/collection.go
- db/collection_test.go
- db/db.go
- db/db_test.go
- db/escape_test.go
- db/index.go
- db/index_test.go
- db/interfaces.go
- db/operations.go
- db/query.go
- db/snapshot.go
- db/snapshot_test.go
- db/transaction.go
- db/transaction_test.go
Fixes #22.
There are a lot of changes here. As part of implementing this new feature (and because I'm worried that #147 was a consequence of too much magic), I decided to simplify the interfaces we're using internally and reduce some of the magic.
Instead of relying on embedded structs like `readOnlyCollection` and `writableCollection`, I've decided to opt for a simpler approach. The main logic for most operations now exists as functions in the __operations.go__ file. Each of these functions accept the pieces that they need as arguments (usually `colInfo` and either `dbReader` or `dbWriter` depending on the type of operation).
Functions which use transactions internally are now split up into two parts. For example, the old `Collection.Update` method is now split into two functions: …
> Implement database transactions

- db/collection_benchmark_test.go
- db/db_test.go
- db/query_benchmark_test.go
- db/snapshot_benchmark_test.go
- db/transaction_benchmark_test.go
~~Still WIP because I want to add more benchmarks~~ (update: no longer WIP). After #152 is merged, I'll change the base branch for this PR to master.
Fixes #25.
Initial results:
```
BenchmarkInsert-12          	     100	  23137166 ns/op
BenchmarkFindByIDHot-12     	  200000	      6269 ns/op
BenchmarkFindByIDCold-12    	    3000	    720604 ns/op
BenchmarkUpdateHot-12       	     100	  18108763 ns/op
BenchmarkUpdateCold-12      	     100	  25675224 ns/op
BenchmarkFindAll100-12      	    5000	    299330 ns/op
BenchmarkFindAll1000-12     	      50	  30901471 ns/op
BenchmarkDelete-12          	     100	  13867095 ns/op
```
Right away I can tell that `Insert`, `Update`, and `Delete` are a lot slower than I expected (on the order of 10-25ms). In contrast, `FindByID` takes ~6µs, which is a …
> Add database benchmarks

- core/core.go
- p2p/node.go
Up until now, we have only been listening on the local address 127.0.0.1. This PR should make it possible for two peers on different networks to find one another (even if they are behind NATs).
> Listen on public addresses and enable relay

- README.md
Removed butt URL for mesh-ganache-cli reference and replaced with existing DockerHub link.
> Removed butt URL for mesh-ganache-cli reference

- cmd/demo/subscribe_to_orders/main.go
Without this check, the __subscribe_to_orders__ demo script would not detect when the server end of the connection is closed and would hang indefinitely.
> Check for errors in order subscription script

- p2p/node.go
This should help orders propagate faster while still keeping bandwidth requirements fairly low.
> Increase maxReceiveBatch and maxShareBatch

- db/col_info.go
- db/collection.go
- db/collection_test.go
- db/operations.go
- db/snapshot.go
- db/snapshot_test.go
Required for #73 and #167.
The implementation is to keep the count of all models in the collection stored in a separate key and update it on each insert/delete. This does reduce insert/delete performance slightly, but we think it is worth it since it changes count operations from `O(N)` to `O(1)`.
```diff
- BenchmarkInsert-12                                        	  100000	     16363 ns/op
+ BenchmarkInsert-12                                        	  100000	     19481 ns/op
- BenchmarkDelete-12                                        	  100000	     15089 ns/op
+ BenchmarkDelete-12                                        	  100000	     16921 ns/op
- BenchmarkTransactionInsert100-12                          	    3000	    903916 ns/op
+ BenchmarkTransactionInsert100-12 …
```
> Add a new Count method for counting all models in a collection

- zeroex/asset_data_decoder.go
Without this check, the `AssetDataDecoder` can panic due to the index being out of bounds.
> Return an error if asset data is too short

- db/col_info.go
- db/collection.go
- db/collection_benchmark_test.go
- db/collection_test.go
- db/db.go
- db/escape_test.go
- db/global_transaction.go
- db/global_transaction_test.go
- db/index_test.go
- db/operations.go
- db/query_benchmark_test.go
- db/query_test.go
- db/snapshot_benchmark_test.go
- db/snapshot_test.go
- db/transaction.go
- db/transaction_benchmark_test.go
- db/transaction_test.go
- meshdb/meshdb.go
Required for #73 and #167.
This feature will allow us to maintain consistency when modifying the database state for two or more collections at once.
> db: Implement global transactions

- db/collection.go
- db/global_transaction.go
- db/global_transaction_test.go
- db/operations.go
- db/transaction.go
- db/transaction_test.go
Fixes a bug in `Count`. Before this PR, calling `Insert` or `Delete` inside of a transaction could result in the count becoming incorrect.
After https://github.com/0xProject/0x-mesh/pull/176 is merged, I'll rebase this off of master and change the base branch for the PR.
Coincidentally, this should also improve performance when inserting or deleting multiple models in a single transaction.
> Fix bug in Count when models are inserted/deleted inside a transaction

- zeroex/order.go
Fixes: #178 
Add custom MarshalJSON method for OrderEvent so that `fillableTakerAssetAmount` is sent over the wire as a stringified amount and never in scientific notation.
> Fix `fillableTakerAssetAmount` in order event subscription payload

- core/core.go
- ethereum/blockchain_lifecycle.go
- ethereum/blockwatch/block_watcher.go
- ethereum/blockwatch/block_watcher_test.go
- ethereum/blockwatch/client.go
MarkM mentioned Mesh not firing events when connected to Kovan on our discord.
Turns out Kovan uses a different structure for block headers then mainnet that isn't `rlp` compatible and since we are using go-ethereum's `EthClient`, it is generating incorrect block hashes for Kovan blocks. More details on this discrepancy between mainnet and Kovan here: https://github.com/ethereum/go-ethereum/pull/18166.
The fix is to use a raw JSON RPC request to `eth_blockByNumber` which returns a pre-computed block hash that is always properly formatted instead of re-computing the block hash given the block header struct returned from `EthClient`'s `BlockByNumber()` method.
Additionally, this PR also logs all BlockWatcher errors, which were not being logged previously.
> blockwatch/core: Fix Kovan incorrect block hash bug

- cmd/mesh/rpc_handler.go
- constants/constants.go
- rpc/client.go
- rpc/client_server_test.go
- rpc/service.go
Fixes: https://github.com/0xProject/0x-mesh/issues/170
The MARKET Protocol team requested the addition of a heartbeat subscription to the Mesh WS interface so that they could properly handle lost connections that might otherwise be hard to detect.
> rpc/mesh: Add heartbeat subscription

- zeroex/order_validator.go
This is a temporary fix to address: https://github.com/0xProject/0x-mesh/issues/191
Currently any attempted batch validation including more then 300 orders is likely to fail against Infura and Geth. 
I consider this a temporary fix because the size of orders is variable and the limits on the API calls are most likely triggered by payload size. A more robust solution will involve computing the expected payload size, and also recursive splitting of the payload if the limit was not successfully avoided (e.g., Infura changes their limits without warning -- which has happened before).
> zeroex: Reduce the order validation chunk size from 500 to 300

- DOCUMENTATION.md
- cmd/mesh-keygen/main.go
- core/core.go
Taking a page [from Geth's playbook](https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options), I think it makes more sense to move the database file and private key file into a single directory called `DATA_DIR`. This reduces the number of env vars required and makes it easier to reset Mesh/remove all data associated with it.
> Consolidate database and private key paths into a single env var

- zeroex/order.go
- zeroex/order_test.go
Without this fix, attempting to subscribe to orders will result in an error:
```
RPC_ADDRESS="ws://localhost:60147" ETHEREUM_RPC_URL="http://localhost:8545" go run cmd/demo/subscribe_to_orders/main.go
panic: math/big: cannot unmarshal "\"2000\"" into a *big.Int
goroutine 1 [running]:
main.main()
/Users/alex/programming/go/src/github.com/0xProject/0x-mesh/cmd/demo/subscribe_to_orders/main.go:46 +0x53e
exit status 2
```
This is happening because we implemented a custom `MarshalJSON` method for `OrderEvent` but never implemented the corresponding `UnmarshalJSON` method. I also added a test in __order_test.go__ to cover this case.
> Fix bug when unmarshaling OrderEvent

- DOCUMENTATION.md
- cmd/mesh-keygen/main.go
- core/core.go
- keys/keys.go
- p2p/node.go
- p2p/node_test.go
Fixes https://github.com/0xProject/0x-mesh/issues/146.
I think we should leave the `mesh-keygen` binary in place in case people want more manual control. In most cases, it is not needed.
> Automatically generate private key if needed

- db/global_transaction.go
- db/global_transaction_test.go
I don't think this will actually fix https://github.com/0xProject/0x-mesh/issues/220 but it's something we should fix anyways.
`colLock` prevents new collections from being created while a global transaction is open. It exists in order to ensure that any new collections also respect the `globalWriteLock`. Prior to this change, it was theoretically possible for a new collection to be created after the `globalWriteLock` was locked but before the `colLock` was locked, meaning there's a chance it would not respect the `globalWriteLock`. The new ordering is more correct (although I think the chances of this causing any problems is pretty minuscule).
I also added a short `time.Sleep` to help prevent false positives in `TestGlobalTransaction`.
> db: Change the order of colLock and globalWriteLock

- core/core.go
I realized that the Ethereum RPC URL often includes API keys from providers like Infura. In some cases people don't care about leaking these keys (we even include ours in some documentation to make it easier for people to get started). But there are other cases where it can affect billing or rate-limiting so it's best to play it safe and not log it.
> Don't log Ethereum RPC URL

- db/operations.go
- db/query.go
Fixes #227.
We inspected the bug and determined that, thankfully, it was not a data integrity issue. The problem is that the `db` package is too strict about what keys are expected to exist at what times. It is technically okay for models to be deleted or added concurrently while we are iterating through an index (it just means we don't include those models in the final results). The fix is to simply relax this constraint and not return an error in the `db` package when this happens.
> db: Tolerate a model being deleted while iterating through index keys

- core/message_handler.go
Before:
```json
{
"errors": [
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{}
],
"from": "16Uiu2HAmR4gZRrrq7K3g6PGmFc6ojSFrv8nhjEyWbk42vAQG7VzP",
"level": "trace",
"msg": "order schema validation failed for message",
"time": "2019-07-11T17:25:09-07:00"
}
```
After: 
```json
{
"errors": [
"(root): makerAddress is required",
"(root): takerAddress is required",
"(root): makerFee is required",
"(root): takerFee is required",
"(root): senderAddress is required",
"(root): makerAssetAmount is required",
"(root): takerAssetAmount is required",
"(root): makerAssetData is required",
"(root): takerAssetData is required",
"(root): salt is required",
"(root): exchangeAddress is required",
"(root): feeRecipientAddress is required",
"(root): expirationTimeSeconds is required",
"(root): …
```
> fix log format for order schema validation errors

- core/core.go
- core/message_handler.go
- core/validation.go
Fixes: #233 233
Replace order schema validation on incoming messages with Mesh message schema validation since the orders are wrapped inside a message payload:
```json
{
"MessageType": "order",
"Order": {
"makerAddress": "0x5409ED021D9299bf6814279A6A1411A7e866A631",
"makerAssetData": "0xf47261b0000000000000000000000000871dd7c2b4b25e1aa18728e9d5f2af4c4e431f5c",
"makerAssetAmount": "1000",
"makerFee": "0",
"takerAddress": "0x0000000000000000000000000000000000000000",
"takerAssetData": "0xf47261b00000000000000000000000000b1ba0af832d7c05fd64161e0db78e85978e8082",
"takerAssetAmount": "2000",
"takerFee": "0",
"senderAddress": "0x0000000000000000000000000000000000000000",
"exchangeAddress": "0x48BaCB9266a570d521063EF5dD96e61686DbE788",
"feeRecipientAddress": …
```
> core: Fix message schema validation issue

- examples/javascript_websocket_client/index.js
- examples/javascript_websocket_client/index.ts
> examples: Disable fragmentation of JS WS client payloads

- Makefile
- cmd/mesh-bootstrap/main.go
Fixes #223.
After investigating this, I decided it was cleaner to create a separate executable rather than modify the existing code at __p2p/node.go__. Technically there is some duplicated code but a lot of the configuration is different and we are able to skip almost all the steps in `p2p.Node.Start`.
> Create a separate executable for bootstrap nodes

- core/validation.go
The comment in the code explains why we want to do this. We plan to add support for some known sender addresses out-of-the-box and will eventually allow users to pass in custom validation logic (which can include additional third-party sender addresses).
> Temporarily don't accept orders with a senderAddress

- Gopkg.lock
- Gopkg.toml
- cmd/mesh-bootstrap/main.go
Long-term, we should consider using separate instances for AutoNAT or enabling AutoNAT for all peers when possible (i.e. for non-browser peers with a public IP address). This should work fine for now.
> Enable AutoNAT service in mesh-bootstrap

- p2p/node.go
We observed some cases where two peers could not connect to one another even though both were located in the continental US. It seems like a good idea to slightly increase the default timeout and we might make further adjustments in the future.
> Increase default network timeout from 5 to 10 seconds

- core/core.go
This change makes it so that peers running different versions will still be able to find and communicate with one another as long as we don't break backwards compatibility. If we do break backwards compatibility, we can change the major version to `2`.
> Use major version only for rendezvous string and topic

- cmd/mesh-bootstrap/main.go
- p2p/bootstrap.go
- p2p/node.go
We observed that our bootstrap nodes were connecting to tens of thousands of peers, even though we only have a handful of Mesh nodes running at the moment. Most of the peers were using port 4001, which is the default IPFS port. We think that our DHT was somehow merged with the default IPFS DHT (it's pretty easy to accidentally do this and once it happens they are basically linked forever).
Technically speaking, it isn't a huge problem that a lot of peers are connecting to our bootstrap nodes, but it does have an impact on how quickly our peers can find each other (one of the reasons we decided to spin up our own bootstrap nodes in the first place) and muddies up our logs.
This PR changes the protocol id that we use for the DHT which should keep ours separate from the default IPFS one.
> Use a custom protocol id for our DHT

- zeroex/order_validator.go
This PR makes sure to Marshal the `fillableTakerAssetAmount` field in AcceptedOrderInfo into a string.
Fixes: #256
> zeroex: Marshal AcceptedOrderInfo properly

- cmd/mesh-bootstrap/main.go
- core/core.go
- core/message_handler.go
- loghooks/peer_id_hook.go
- p2p/notifee.go
Summary of changes:
1. Use a [`logrus.Hook`](https://godoc.org/github.com/sirupsen/logrus#Hook) to add a peer ID for all logs when possible.
2. Change "connected to peer" and "disconnected from peer" messages in `mesh-bootstrap` from `Trace` to `Info`. These are the main and only responsibility of bootstrap nodes so it is appropriate to log them.
3. Add a new log message at level `Info` which logs the order hash only for any new valid orders. We still keep the `Trace` message which includes the entire order.
4. Rename some uses of the field name `peerID` to `remotePeerID` for clarity.
> Improve logging

- zeroex/order.go
Simply adding a call to `strings.ToLower()` on all address fields when marshalling a `SignedOrder` to JSON. Tests (run with `make test-all`) pass and functionality seems normal. Please advise if a different approach is preferred.
Should close #257.
Here is the output I got from a `mesh_subscription` message after adding a valid order (compare to sample in original issue).
```json
{
"jsonrpc": "2.0",
"method": "mesh_subscription",
"params": {
"subscription": "0x5375e6c2d24cb11874a79ea90e7851f",
"result": [{
"fillableTakerAssetAmount": "0",
"kind": "EXPIRED",
"orderHash": "0x222f59940699cb7f7743d68e95cc952eabef58dd3ef22629811f0da6ff8b29aa",
"signedOrder": {
"makerAddress": "0x5409ed021d9299bf6814279a6a1411a7e866a631",
"makerAssetData": …
```
> zeroex: remove checksum from address fields in Order when marshalling to JSON

- cmd/mesh-bootstrap/main.go
This will allow bootstrap nodes to advertise the correct public IP address (before they were advertising the Docker subnet address).
> Use AddrsFactory to advertise public IP addresses in mesh-bootstrap

- Gopkg.lock
- p2p/node.go
Currently our logs are filled with a lot of "dial backoff" errors. This happens pretty often when a peer disconnects from the network. This PR reduces the verbosity of those errors to make our logs leaner and more useful.
> Reduce verbosity for dial backoff errors

- zeroex/orderwatch/order_watcher.go
During testing I noticed that OrderEvents consistently had 2 txHashes, with the first one always being the null address. By inspecting the code, I saw we are appending to an array created using `make()` which pre-created len number of zero-value entries. I've decided to fix by reverting to using `[]common.Hash{}` instead of `make()`. Although less efficient, in the subsequent looping over the map, we don't have a readily available index to use in replacing the zero-values and so this feels like the cleanest approach.
I additionally noticed we weren't instantiating `TxHashes` in the cleanup job, which would have caused later code to attempt to treat a `nil` value as an instantiated map.
> orderwatch: Remove null txHashes & fix uninstantiated map issue

- cmd/mesh-bootstrap/main.go
- core/core.go
- loghooks/key_suffix_hook.go
- loghooks/key_suffix_hook_test.go
This PR will help fix field mapping conflicts in Elasticsearch. When we have two separate logs with the same field name but different types, Elasticsearch cannot correctly index them, which often results in log messages being lost. If we add a type suffix, it will no longer be possible to have the same field name but different types.
> Add type suffixes to all keys when logging

- zeroex/orderwatch/event_decoder.go
Fixes: #278 
Protect all read/writes to known contract addresses with a mutex so that they are concurrency-safe.
> orderwatch: Fix concurrent read/write issue in EventDecoder

- ethereum/blockwatch/block_watcher.go
> blockwatch: Handle both Parity and Geth "unknown block" errors gracefully

- core/core.go
- expirationwatch/expiration_watcher.go
- expirationwatch/expiration_watcher_test.go
- zeroex/orderwatch/order_watcher.go
As mentioned in #96, we are moving towards making our asynchronous APIs more consistent across all packages. This PR applies the new conventions to the `expirationwatch` package only.
One consequence of making this change one package at a time is that there are some places where we need to awkwardly bridge the various old asynchronous coding styles with the new style. Some things will get uglier before they get prettier. For example, we are now creating contexts and storing cancel funcs for the sole purpose of passing them into `expirationwatch.Watcher.Watch`. But after all packages transition to the new conventions, we will be able to inherit from a parent context instead of creating a new one.
Since we are changing the API anyways, I also wanted to rename `Start` to `Watch` and …
> expirationwatch: Use consistent asynchronous API

- p2p/bootstrap.go
These are temporary backup nodes operated by the libp2p community on a best-effort basis.
Fixes #255
> Add backup bootstrap nodes

- cmd/mesh/main.go
- core/core.go
Related to #96.
Since I was already changing some related code, I went ahead and fixed #299 in this PR too.
> Use consistent asynchronous API for core package

- cmd/mesh/main.go
- cmd/mesh/rpc_handler.go
- rpc/client_server_test.go
- rpc/server.go
> rpc: Use consistent asynchronous API

- core/core.go
- ethereum/eth_watcher.go
- ethereum/eth_watcher_test.go
> ethereum: Use consistent asynchronous API for ETHWatcher

- core/core.go
Fixes #288.
Instead of just returning a better error message, this PR automatically removes extraneous quotes from any string parameters in `core.Config`.
> core: Automatically unquote config fields if needed

- db/global_transaction_test.go
- db/transaction_test.go
See https://github.com/0xProject/0x-mesh/pull/211. It looks like we didn't go far enough in that PR and some transaction tests are still occasionally failing on CI. This PR increases the sleep duration from 5ms to 50ms.
> Increase sleep duration in some transaction tests (again)

- Makefile
Fixes #183. 
Go offers a `--timeout` flag which will cause `go test` to fail if the tests for any package take too long. It would technically be better to go through each test and eliminate situations where the test could hang. In practice, that can be difficult and it is easy to miss some edge cases. I think the `--timeout` flag will be good enough.
> Add a timeout of 30s (per package) for tests

- core/core.go
- core/core_test.go
- db/collection_test.go
- db/escape_test.go
- db/global_transaction_test.go
- db/index_test.go
- db/integrity_check_test.go
- db/query_benchmark_test.go
- db/query_test.go
- db/snapshot_test.go
- db/transaction_test.go
- ethereum/blockwatch/block_watcher_test.go
- meshdb/meshdb.go
- meshdb/meshdb_test.go
> Remember to call db.Close and meshdb.Close in tests

- cmd/mesh/rpc_handler.go
- core/core.go
- core/message_handler.go
- zeroex/orderwatch/order_watcher.go
> orderwatch: Use consistent asynchronous API 

- cmd/mesh/main.go
- cmd/mesh/rpc_handler.go
- core/core.go
- db/escape.go
- db/escape_test.go
- ethereum/blockwatch/block_watcher.go
- ethereum/blockwatch/block_watcher_test.go
- ethereum/eth_watcher.go
- p2p/node.go
- rpc/server.go
- zeroex/order_validator.go
Fixes #96.
Depends on #307. After that PR is merged I'll change the base branch for this one to `development`.
Summary of changes:
- Make `core.App.Start` blocking.
- Remove `core.App.Stop`.
- Avoid `log.Panic` and `log.Fatal` whenever possible (there are some lingering cases where e.g., we pass a function into another function and don't have a good way to return errors).
- Remove the `blockwatch.Watcher.Errors` channel. For non-critical errors, we log them in `blockwatch.Watcher` directly. For critical errors, we return them in `blockwatch.Watcher.Watch`. This makes `blockwatch` more aligned with the rest of our async code.
- Don't start any goroutines without a way to stop them (usually by waiting for `ctx.Done()` but sometimes with short timeouts or other signals).
> Final changes to make all code follow our async conventions

- ethereum/blockwatch/block_watcher.go
@fabioberger I think the verbosity of this log should change from `Info` to `Trace`. Whenever I run Mesh locally for quick tests, this log message is taking up a large percentage of the total number of logs. I don't think it is helpful to see hundreds of logs for what is a pretty common occurrence. What do you think?
> Reduce verbosity of "fetching block logs" message

- core/core.go
- ethereum/blockwatch/block_watcher.go
In `v1.0.6-beta` we waited for for block events to backfill before doing anything else in `core.App.Start`. That feature was accidentally lost when some of my recent PRs changed the way our asynchronous code works. This PR makes our initialization process closer to how it was in `v1.0.6-beta`, so we wait for backfilling to finish before doing some steps in `core.App.Start`.
In this PR, the order of initialization is:
1. Start the snapshot expiration watcher.
2. Start the order watcher.
3. Start the ETH balance watcher.
4. Backfill block events (this blocks).
5. Start the block watcher.
6. Start the p2p node.
The main difference is that we won't send orders to/receive orders from any peers until after backfilling has been completed. This is important because if we are behind on blocks we …
> Wait for block events to backfill in core.App.Start

- core/core.go
- core/message_handler.go
- core/validation.go
- rpc/client.go
- rpc/client_server_test.go
- rpc/clients/typescript/src/index.ts
- rpc/clients/typescript/src/types.ts
- rpc/clients/typescript/src/ws_client.ts
- rpc/types.go
- zeroex/order_validator.go
- zeroex/order_validator_test.go
- zeroex/orderwatch/order_watcher.go
> core: Handle stored orders differently if flagged for removal

- .gitattributes
- cmd/cut-release/main.go
- Update version in beta `docker-compose.yml` file
- Instruct Github to auto-collapse generated MD files in PR review.
> cmd: `cut-release` improvements

- rpc/clients/typescript/tsconfig.json
So types can be used in downstream projects.
> client: Add Typescript Declaration generation option

- CHANGELOG.md
- zeroex/order_validator.go
- zeroex/orderwatch/order_watcher.go
0x has this quirk where an order can be _partially fillable_. What this means is that the order maker has a sufficient balance/allowance to fill some portion of the outstanding order but _not the total remaining amount_. We used to consider any order that can be filled for a non-zero amount as valid. This PR introduces a breaking change to instead consider any order where the `fillableAmount` != `remainingAmount` to be considered invalid. 
After doing an empirical analysis of existing 0x orderbooks, the only orders that we've found in this state were mistakes. Additionally, it makes batch fill methods less effective, since the 0x smart contracts do not validate balance/allowance amounts before fills but rely on the`token transfer` reverting to detect insufficient funds/allowance. This can …
> zeroex: Treat partially fillable orders as invalid

- CHANGELOG.md
- core/core.go
I noticed we weren't de-duping orders sent over JSON-RPC to the Mesh node, so I fixed this.
> core/rpc: Dedup orders received via `mesh_addOrders` endpoint

- Gopkg.lock
- Gopkg.toml
- core/core.go
- p2p/node.go
Fixes #295.
[go-libp2p-peerstore](https://github.com/libp2p/go-libp2p-peerstore) actually already ships with support for using LevelDB as the backing datastore. Since https://github.com/syndtr/goleveldb/pull/288 already adds support for WebAssembly, all we have to do is use our fork of goleveldb and hook the different pieces together and it should work 🤞 
It's difficult to write tests that run in the browser without having a Wasm-compatible transport, so we won't be able to thoroughly test that the peerstore works in the browser until later on. However, I was able to run a slightly modified version of the [go-libp2p-peerstore](https://github.com/libp2p/go-libp2p-peerstore) tests against our fork of LevelDB in Wasm. The test suite there is fairly comprehensive and everything passed.
> Use LevelDB as a backing for our PeerStore

- .circleci/config.yml
- .gitignore
- GO_LICENSE
- Gopkg.lock
- Gopkg.toml
- meshdb/browser-tests/index.html
- meshdb/browser-tests/main.go
- meshdb/browser-tests/resources/browserfs-1.4.3.js
- meshdb/browser-tests/resources/qunit-2.9.2.css
- meshdb/browser-tests/resources/qunit-2.9.2.js
- meshdb/browser-tests/resources/wasm_exec.js
- meshdb/meshdb_browser_test.go
- package.json
- test-wasm/go_js_wasm_exec
- yarn.lock
This PR adds full browser support for the `meshdb` package (and the `db` package, which it depends on). Fixes #297.
I've also added a new test which uses QUnit bindings. The test is compiled to WebAssembly and run in a headless browser as part of `go test`. We might be able to clean up and simplify the process in the future (e.g. by using a tool which automatically builds the required __index.html__ file instead of checking it into git), but it should be good enough for now.
I think our testing strategy should be to run all unit tests in Node.js because it's easier and allows us to use the same test files we already have (any file ending in `_test.go`). We only need to run high-level integration tests in the browser
This depends on two external PRs. I modified our __Gopkg.toml__ file to …
> meshdb: Add browser support

- README.md
- docs/USAGE.md
Based on feedback we have received from users, our current documentation does not do a great job of explaining what Mesh is at a high level and how it can be used. This PR helps address that by adding an "Overview" section to the README and clarifying on the purpose of the JSON-RPC API.
> Add an overview section to README and clarify purpose of JSON-RPC API

- core/core.go
- core/validation.go
- expirationwatch/expiration_watcher.go
- zeroex/order_validator.go
- zeroex/order_validator_test.go
Fixes #341.
The problem was occurring because we did not respect the expiration buffer when validating incoming messages. This PR fixes the issue and also uses the same function `IsExpired` in both the expiration watcher and the order validator to avoid these kinds of issues in the future.
> zeroex: Add order expiration buffer to zeroex.OrderValdiator

- CHANGELOG.md
- ethereum/blockwatch/client.go
Fixes: #342 & #323 
Use `hexutil.EncodeBig` instead of `Bytes2Hex` when converting `BigInt` to hex to avoid leading zeroes which are considered invalid encoding by the Ethereum JSON-RPC spec.
> blockwatch: Fix number to hex encoding bug

- rpc/clients/typescript/test/ws_client_test.ts
Fixes: #351 
Refactor reconnected test so that only the first connection is dropped, not the subsequent one.
> rpc: Fix race-condition in TS client test

- keys/fs.go
- keys/fs_js.go
- keys/keys.go
- keys/keys_test.go
This PR adds browser support to the `keys` package. We do this by mocking a small part of the filesystem using `localStorage`. This allows browser to retain the same private key and peer ID between refreshes.
> keys: Add browser support

- p2p/node.go
https://ifconfig.me responds with different results depending on the value of the `User-Agent` header. For browser environments, it responds with HTML and for non-browser environments it responds with your IP address in plain text. Adding `/ip` to the URL results in the same behavior regardless of user agent.
> p2p: Fix public IP hack for browser environments

- cmd/mesh-bootstrap/main.go
- p2p/bootstrap.go
Related to #360. If each bootstrap nodes is advertising a WebSocket address, we should also update our bootstrap list to include those addresses.
This PR assumes that each bootstrap node will be listening for TCP connections on port `60558` and WebSocket connections on port `60559`.
> p2p: Add WebSocket addresses to bootstrap list

- cmd/mesh-bootstrap/Dockerfile
- cmd/mesh-bootstrap/main.go
This PR allows bootstrap nodes to advertise any multiaddress. Prior to this, they were only advertising TCP addresses of the form `/ip4/172.12.0.3/tcp/60559`. This is a problem because browser-based peers can't speak TCP and therefore had no way of connecting to the bootstrap nodes.
This PR consolidates the `P2P_LISTEN_PORT` and `PUBLIC_IP_ADDRS` environment variables into a single one called `P2P_ADDRS`. It's a comma-separated list of multiaddresses which the node will both bind to and advertise.
Importantly, this will allow us to advertise both different protocols and different addresses for each protocol. The full list of multiaddresses that will be advertised by bootstrap nodes in the near term is:
1. TCP with IPv4 address.
2. TCP with IPv6 address.
3. TCP with domain name.
4. …
> cmd/mesh-bootstrap: Allow bootstrap nodes to advertise arbitrary multiaddrs

- cmd/mesh-bootstrap/main.go
#360 was the right idea, but I ran into a problem when trying to run the new code on a Docker container with a non-local IP address. We need to separate the env vars into bind addresses and advertise addresses. You can only bind to localhost or an IP address in the Docker subnet, but for other peers who want to connect to us, we need to advertise the public IP address(es).
> Separate addrs into bind and advertise addrs for bootstrap nodes

- core/message_handler.go
In browser environments, order hashes were getting logged as `[]byte` instead of a hex string. This PR fixes the issue.
> core: Force order hash to log as hex string instead of []byte

- cmd/mesh/main.go
- ethereum/blockwatch/block_watcher.go
Should fix #319. It's difficult to test because I can't reproduce the original error.
I did do a bit of manual testing by adding some code to forcibly close the database after 30 seconds. I can confirm that in this case Mesh exited and logged the error as expected.
> cmd/mesh: Exit the process if the database is closed

- loghooks/key_suffix_hook.go
- loghooks/key_suffix_hook_test.go
I noticed the correct suffix was not being added for certain types in the logs. This PR should fix the issue.
> loghooks: Add some previously uncovered types to KeySuffixHook

- integration-tests/browser/src/index.ts
- integration-tests/integration_test.go
The previous version of the integration tests did not cover the `onOrderEvents` callback and instead looked directly at the logs coming from Mesh (e.g. the `core` and `p2p` packages). This PR improves the tests by explicitly logging events that come through the `onOrderEvents` callback and then checking for the logs we expect.
I also thought about checking the `mesh_subscribe orders` RPC endpoint, but doing that right now is prohibitively complicated due to unpredictable timing in the order of events. It's hard to make sure we subscribe to the RPC endpoint in time to receive the order, and if we aren't subscribed, we'll simply miss it. In addition, unlike the `onOrderEvents` callback, the `rpc` package is already tested elsewhere. So in order to make sure the standalone node receives the …
> Incorporate onOrderEvents callback in integration tests

- integration-tests/browser/package.json
- integration-tests/browser/src/index.ts
- integration-tests/browser/yarn.lock
- integration-tests/integration_test.go
This PR fixes an issue where the integration tests were failing due to the hard-coded orders expiring. Instead of using hard-coded orders we generate and sign a new order in both the browser node and standalone node.
> Fix integration tests by generating and signing fresh orders

- db/global_transaction_test.go
- db/transaction_test.go
This PR rewrites the transaction exclusion tests to avoid using `time.Sleep` when possible. Hopefully this will help reduce the rate of sporadic failures on CI.
Fundamentally, these tests are hard to write because in some cases we are checking that events _do not_ to occur over a certain time frame. Another complication is that CI performs differently (especially when running the tests in the browser) and has a different timing for certain events.
The tests are still not perfect and there are some cases where a difference in timing can lead to a false positive, but this PR should still make things a lot better.
> Remove sleep from transaction exclusion tests

- zeroex/orderwatch/order_watcher.go
Fixes: #364 
This PR fixes the issue of expired orders were being re-added to OrderWatcher when fill/cancel events for that order trigger. Instead, the fill/cancel order events should still fire, but the order should not be re-added.
> orderwatch: Avoid re-adding expired orders to OrderWatcher

- Gopkg.lock
- Gopkg.toml
- integration-tests/browser/package.json
- p2p/host.go
- p2p/node.go
- p2p/node_test.go
Fixes #387.
I originally thought we should create our own `ConnectionManager` to implement this feature, but after digging more into the libp2p code, I don't think that will work. `ConnectionManager` is only responsible for pruning existing connections and doesn't really have the ability to prevent connections from being established in the first place. There is also an incentive to do this at the lowest abstraction level possible to minimize the resources that a peer with a banned IP address can use. Luckily, what we need is basically already implemented in the `swarm` package (see [`Swarm.Filters`](https://godoc.org/github.com/libp2p/go-libp2p-swarm#Swarm)).
Unfortunately `libp2p.New` does not currently expose any way to configure or access the underlying swarm. To workaround this issue, …
> p2p: Add ability to ban IP addresses

- CHANGELOG.md
This PR adds a missing CHANGELOG entry and also proposes a new approach where we already add them under the next proposed version we will publish. As the types of changes added evolve, the engineer implementing them will adjust the upcoming version accordingly.
> changelog: Add missing changelog

- CHANGELOG.md
- zeroex/orderwatch/order_watcher.go
Fixes: #190 
Currently, we aren't updating an orders `fillableTakerAssetAmount` nor it's `lastUpdated` timestamp in the DB when processing a contract event impacting it _unless_ it is being unwatched or re-watched. This PR makes it such that we always update an order's DB entry, no matter what the event so that the `lastUpdated` and `fillableTakerAssetAmount` in the DB is always accurate.
> orderwatch: Update lastUpdated and fillableTakerAssetAmount for order in DB

- zeroex/orderwatch/order_watcher.go
Fixes a DB transaction deadlock accidentally introduced in the v4.0.0-beta release.
> orderwatch: Permanently delete orders from DB from within txn to avoid a deadlock

- core/core.go
- core/message_handler.go
- core/validation.go
- zeroex/order_validator.go
- zeroex/orderwatch/order_watcher.go
This PR:
- Removes some unused/unnecessary vars/types from `zeroex`
- Consolidates the RejectedOrderStatuses in `zeroex` so that developers wanting to know all the rejection statuses they need to handle can look at one authoritative place.
I considered moving the RejectedOrderStatuses to a separate module but they are _mostly_ used in `zeroex` and make up part of the interface of the `OrderValidator` method `BatchValidate`. It didn't seem like the best solution.
> zeroex,core: Consolidate RejectedOrderStatuses

- CHANGELOG.md
- browser/ts/index.ts
- integration-tests/browser/src/index.ts
This was always intended to be an optional field. The fact that it's required in the `Config` type was just an oversight.
> Make verbosity field optional in TypeScript Config type

- CONTRIBUTING.md
- docs/summary.md
This move will make the guide show up in the GitHub UI when opening a new pull request. I also updated the guide to specify when to use the `development` branch.
> Move docs/development.md to CONTRIBUTING.md and update it

- .circleci/config.yml
- rpc/clients/typescript/package.json
Related to #428. We can take even more steps if needed; this is just the low-hanging fruit.
> Move some deps to devDependencies for TS RPC client

- p2p/bandwidth_checker.go
- p2p/bandwidth_checker_test.go
- p2p/node.go
- p2p/node_test.go
Fixes https://github.com/0xProject/0x-mesh/issues/119.
This PR implements low-level rate-limiting and bans offending peers by their IP address. Currently, the limit on bandwidth usage is set conservatively high at 100 MiB/s. We can lower this limit over time as we get a better sense for what real world usage looks like.
This PR also will cause Mesh to log bandwidth statistics every 5 minutes, which will help us understand how much bandwidth is being used by each peer and each protocol over time. Technically, it would probably be better to report these statistics via Prometheus. However, since we already have the proxy and authentication infra set up for logging+EFK, I think it is okay to log them for now.
Also note that in order for this rate-limiting strategy to be effective we need to …
> Implement low-level rate-limiting

- CHANGELOG.md
- browser/ts/index.ts
- core/validation.go
- docs/db_syncing.md
- docs/rpc_api.md
- integration-tests/integration_test.go
- rpc/clients/typescript/src/index.ts
- rpc/clients/typescript/src/types.ts
- rpc/clients/typescript/src/ws_client.ts
- rpc/clients/typescript/test/ws_client_test.ts
- zeroex/order.go
- zeroex/order_js.go
- zeroex/order_test.go
- zeroex/ordervalidator/order_validator.go
- zeroex/ordervalidator/order_validator_test.go
- zeroex/orderwatch/decoder/event_decoder.go
- zeroex/orderwatch/decoder/event_decoder_js.go
- zeroex/orderwatch/decoder/event_decoder_test.go
- zeroex/orderwatch/order_watcher.go
- zeroex/orderwatch/order_watcher_test.go
- zeroex/orderwatch/topics.go
Fixes: #396 
This PR adds the parsed order-relevant contract events to the OrderEvents emitted from the JSON-RPC `orders` subscription. At first we thought we might be able to emit a top-level order event _for every_ contract event. This is however not possible to do in a robust way. The reason for this is two fold:
1. We are only able to execute `eth_call` requests at the boundaries between blocks. We are unable to execute them at particular transaction indexes within blocks. What this means is that we can only query the state of orders before or after _all_ transactions (and their associated events) within a block have been processed. This leaves us with an end state for each order after the block is processed, and we are tasked with figuring out how the individual contract events …
> orderwatch,rpc: Supply parsed contract events in emitted OrderEvents

- CHANGELOG.md
- zeroex/orderwatch/order_watcher.go
- zeroex/orderwatch/order_watcher_test.go
This PR fixes a bug in OrderWatcher where we were not updating an order's fillableTakerAssetAmount in the DB if an order was _partially_ filled, or if it's fillability increased due to a block re-org.
> orderwatch: Fix fillableTakerAssetAmount DB update bug

- .circleci/config.yml
- cmd/cut-release/main.go
The `cut-release` tool had the following issues that this PR fixes:
- Tried to update no longer existent `docker-compose.yml`
- Didn't generate updated doc MD file for Browser package
- `deployment_with_telemetry` file was missing file suffix
- `development.md` file no longer exists
> cut-release: Fix outdated elements of script

- browser/go/main.go
- browser/ts/index.ts
- core/core.go
- ethereum/contract_addresses.go
- integration-tests/browser/src/index.ts
This PR adds support for declaring a custom network ID and custom contract addresses. This is primarily intended for testing purposes and allows Mesh to be used with local Ethereum networks other than Ganache.
> Add support for custom network ID/custom contract addresses

- p2p/bandwidth_checker.go
- p2p/bandwidth_checker_test.go
See https://github.com/libp2p/go-libp2p-core/issues/65. We're still checking bandwidth and logging in cases where we *would have* banned a peer.
> Temporarily disable bandwidth-based rate-limiting

- CHANGELOG.md
- ethereum/contract_addresses.go
Apparently the fixed `DevUtils.sol` contract has not been re-deployed to Kovan until now. This PR updates it's address.
> ethereum: Update kovan DevUtils.sol address

- CHANGELOG.md
- core/core.go
- p2p/bootstrap.go
Update pubSubTopic, rendezvous string and DHT ID so that the V3 Mesh network is separate from the V2 network.
> p2p: Segregate V3 Mesh network from V2 network

- core/core.go
There is a bug where Mesh can crash with a nil pointer exception if `GetStats` is called before we have pulled any block header data from Ethereum. I only observed this happening when I reduced `logStatsInterval` locally for debugging purposes, but hypothetically this could happen in a real Mesh node too.
> core: Fix issue where GetLatestBlock can sometimes return nil

- core/core.go
- core/message_handler.go
The `GetOrdersToShare` function gets a set of orders from the mesh database to share with other peers. The current strategy for selecting orders to share is simply to choose a random segment of the valid orders in the database's snapshot of length `max`. This strategy works well---albeit imperfectly---when `(number of valid orders)` is reasonably close to `max`, but as the number of valid orders climbs, the risk of some orders not being propagated to peers increases. 
A simple strategy to mitigate this issue is to use a `round robin strategy` for selecting orders. This strategy will select orders by starting at the "beginning" of the database's collection of orders and working all the way up to the last orders in the database. Once the top order has been shared, the strategy loops around …
> core/message-handler: round robin order sharing

- core/core.go
- core/message_handler.go
- p2p/bandwidth_checker_test.go
- p2p/node.go
- p2p/node_test.go
In the current version of Mesh, we do not immediately share orders that are received via JSON-RPC and validated. Instead, we are currently storing them and then relying on the round-robin sharing process for sharing existing orders in the database.
That approach is really inefficient and possibly explains the discrepancy we are seeing in the number of orders held by each Mesh node. This PR addresses the issue by immediately sharing orders received via JSON-RPC (after validation).
> Immediately share orders after they are received via JSON-RPC

- docs/deployment_with_telemetry.md
Gitbook renders this differently than GitHub. Adding back ticks should fix the issue.
> Fix formatting issue in telemetry gudie

- cmd/mesh-bootstrap/main.go
Fixes #447.
The idea is that bootstrap-only nodes will run with `ENABLE_RELAY_HOST=false` and relay-only nodes will run with `ENABLE_RELAY_HOST=true`. The only other functional difference is that the bootstrap nodes are hard-coded in: https://github.com/0xProject/0x-mesh/blob/90c3d03941d328b5f7f92abcc5b0654c7d250bc3/p2p/bootstrap.go#L19
> Add ENABLE_RELAY_HOST env var for bootstrap nodes

- CHANGELOG.md
- browser/go/main.go
- browser/ts/index.ts
- constants/constants.go
- core/core.go
- core/core_test.go
- core/validation.go
- docs/rpc_api.md
- meshdb/meshdb.go
- meshdb/meshdb_test.go
- rpc/client.go
- rpc/clients/typescript/src/types.ts
- scenario/scenario.go
- zeroex/order.go
- zeroex/orderwatch/order_watcher.go
- zeroex/orderwatch/order_watcher_test.go
- zeroex/orderwatch/slowcounter/slow_counter.go
- zeroex/orderwatch/slowcounter/slow_counter_test.go
Fixes #431.
This PR is still a WIP but I'm opening it now so we can discuss the progress so far. This is an implementation of the idea we've been discussing on Slack and a solution to the problem of finite database storage. To quickly re-summarize the idea:
When storage space is plentiful, we start without any kind of limit on expiration time. As the database fills up, we enforce a limit on the maximum expiration time. Any orders that expire after that time will be removed. If more orders keep coming in we can lower the expiration time and remove more orders.
So far this PR adds an index on `ExpirationTime` and implements a new method called `TrimOrdersByExpirationTime` which contains the bulk of the core logic for this feature. There are still some challenges around how to use this …
> core, orderwatch, meshdb: Implement a dynamically decreasing max expiration time for orders

- CHANGELOG.md
- meshdb/meshdb.go
- zeroex/orderwatch/order_watcher.go
Fixes: #459
This PR:
- Adds a process to OrderWatcher that checks for orders that have been flagged for removal and should now be permanently deleted every 5 minutes.
- Stops updating an order DB entry's `lastUpdatedTime` when the entry is in-fact not updated (i.e., when we revalidate the order but no change to fillability was found). This could cause an order from a particularly active maker to stick around indefinitely despite being expired/cancelled/fullyFilled, because the changes in the maker's balance would cause this order to constantly be re-validated and it's `lastUpdatedTime` to constantly get bumped up.
- Slightly increases permanentlyDeleteAfter to 25 block depth to account for us flagging an order for removal due to UTC expiry, but it still potentially getting …
> orderwatch: Check for stale `removed` orders more frequently

- CHANGELOG.md
- browser/go/main.go
- browser/ts/index.ts
- cmd/mesh/rpc_handler.go
- core/core.go
- core/message_handler.go
- meshdb/meshdb.go
- meshdb/meshdb_test.go
- rpc/client.go
- rpc/client_server_test.go
- rpc/clients/typescript/src/types.ts
- rpc/clients/typescript/src/ws_client.ts
- rpc/service.go
- zeroex/ordervalidator/order_validator.go
- zeroex/orderwatch/order_watcher.go
- zeroex/orderwatch/order_watcher_test.go
Fixes #469. The new feature is an optional parameter for RPC requests and the `addOrdersAsync` method in the TypeScript bindings, so this PR maintains backwards compatibility.
> Implement order pinning

- CHANGELOG.md
- Gopkg.lock
- Gopkg.toml
- p2p/bandwidth_checker.go
- p2p/bandwidth_checker_test.go
Fixes #475.
The current implementation will ban peers if they violate bandwidth limits 4 times over the course of 6 hours. Each violation resets the TTL to 6 hours. If there are no violations over a time span of 6 hours, their count of violations is reset.
This workaround does slightly reduce the resiliency of the Mesh network in the face of spamming attacks, but the impact is minimal and it is much better than having no bandwidth limits in place at all.
> Add workaround for BandwidthChecker issue

- cmd/mesh/rpc_handler.go
- core/core.go
This is critical for tracking metrics like order spreading ratio and order propagation delay.
> Log hash for orders added via RPC or browser callback

- CHANGELOG.md
- Gopkg.lock
- cmd/mesh/main.go
- cmd/mesh/rpc_handler.go
- dockerfiles/mesh/Dockerfile
- docs/deployment.md
- integration-tests/integration_test.go
Allows choosing the JSON-RPC API listening interface and port. Remove RPCPort as it is no longer needed.
Big thanks to @nfeignon for implementing this feature 😄
> Add RPCAddr option for the JSON-RPC API

- CHANGELOG.md
- browser/go/main.go
- browser/ts/index.ts
- core/core.go
- docs/deployment.md
- ethereum/blockchain_lifecycle.go
- ethereum/blockwatch/block_watcher.go
- ethereum/blockwatch/block_watcher_test.go
- ethereum/blockwatch/client.go
- ethereum/dbstack/db_stack_test.go
- ethereum/miniheader/miniheader.go
- expirationwatch/expiration_watcher.go
- expirationwatch/expiration_watcher_test.go
- scenario/scenario.go
- zeroex/order.go
- zeroex/ordervalidator/order_validator.go
- zeroex/ordervalidator/order_validator_test.go
- zeroex/orderwatch/order_watcher.go
- zeroex/orderwatch/order_watcher_test.go
Fixed: https://github.com/0xProject/0x-mesh/issues/419 and https://github.com/0xProject/0x-mesh/issues/418
This PR:
- Refactors Mesh to emit order expiration events when orders are expired according to the latest block timestamp. We no longer emit UTC-based expiration events. 
- An order can now become unexpired, if a block re-org causes the latest block timestamp to be earlier than it's predecessor. We therefore added the `UNEXPIRED` order event type.
- Removes the expiration buffer config as it is no longer needed.
> Remove expiration buffer config and emit expiry events based on block timestamp

- CHANGELOG.md
- zeroex/order.go
- zeroex/order_test.go
- zeroex/orderwatch/decoder/event_decoder.go
- zeroex/orderwatch/decoder/event_decoder_test.go
- zeroex/orderwatch/order_watcher.go
This PR fixes a bug in the GO RPC client  that was most likely introduced in `5.0.0-beta`. The bug occurred when subscribing to order events and receiving one with one or more contract events:
```
json: cannot unmarshal object into Go struct field ContractEvent.Parameters of type zeroex.ContractEventParameters
```
This PR fixes the bug by adding an `UnmarshalJSON` event for each type of contract event.
> Fix bug in Go RPC client when unmarshaling contract events

- loghooks/key_suffix_hook.go
I was looking at the logs in Kibana and found that fields would sometimes have duplicated type suffixes. This was happening because fo the way `KeySuffixHook` iterated over a map while making edits to that same map in each iteration. The new implementation creates a new map to avoid the issue.
> Fix bug in KeySuffixHook that caused double suffixes

- docs/summary.md
I'm guessing a bad merge kept this around. It's been replaced by ` * [Deploying a Telemetry-Enabled Mesh Node](deployment_with_telemetry.md)`
> docs: Remove dead link from sidebar

- browser/go/main.go
- browser/ts/index.ts
The `Config` object in the TypeScript bindings was incorrectly using capital letters for some fields instead of lowercase letters. This bug meant that the fields were not passed through and interpreted correctly by the Go code.
> Make TypeScript config parameters lowercase

- examples/browser/README.md
- examples/go/README.md
This will also help fix an issue with broken links on GitBook (seems that when linking to directories, GitBook assumes that a __README.md__ file exists and tries to link to it even if it's not there).
> Add a README for both browser and Go examples

- docs/deployment_with_telemetry.md
Now that we use `RPC_ADDR` to specify the port, we need to set it to `mesh:60557` since the default is now `localhost:*` but we specifically port map `60557`.
> docs: Fix docker-compose.yml example

- .circleci/config.yml
- dockerfiles/mesh-bootstrap/Dockerfile
- dockerfiles/mesh/Dockerfile
There have been some security fixes since Go 1.12.9. See https://golang.org/doc/devel/release.html#go1.12.
> Upgrade to Go 1.12.13

- cmd/cut-release/main.go
The docker images is now being set to a specific version instead of `latest`. This PR updates the regex to reflect this change so that it is properly updated.
> cut-release: Fix docker image version regex 

- examples/go/subscribe-to-orders/main.go
> Improve formatting for subscribe-to-orders example

- CHANGELOG.md
- Gopkg.lock
- Gopkg.toml
- p2p/banner/banner.go
- p2p/banner/banner_test.go
This PR removes a previous hack which granted immunity from bandwidth banning for any peer using a relayed connection. In the past, this was blocked by https://github.com/0xProject/0x-mesh/issues/390 and https://github.com/libp2p/go-libp2p-circuit/pull/80.
This change also required updating some libp2p deps in order to get the full mutliaddress for relayed connections.
> Enforce rate limit on relay addresses

- p2p/banner/banner.go
We're still seeing a lot of false positives due to https://github.com/libp2p/go-libp2p-core/issues/65 and even after introducing a workaround in https://github.com/0xProject/0x-mesh/pull/478 peers are still being banned. This PR increases our tolerance for false positives by allowing up to 10 violations over the course of 1 hour before actually banning a peer (the previous version allowed 4 violations over 6 hours).
> Make bandwidth banning more lenient for false positives

- rpc/clients/typescript/src/ws_client.ts
This PR fixes a bug when trying to add orders via the TypeScript RPC client:
```
Error: Node error: {"code":-32602,"message":"invalid argument 1: json: cannot unmarshal bool into Go value of type rpc.AddOrdersOpts"}
```
> Fix bug for pinned option in TypeScript RPC client

- ethereum/ratelimit/rate_limiter.go
- ethereum/ratelimit/rate_limiter_test.go
The following error was occurring at certain times of day for timezones that are _behind_ UTC:
```
{
"error_string": "rate: Wait(n=1) would exceed context deadline",
"level": "error",
"msg": "core app exited with error",
"myPeerID": "16Uiu2HAkws8tB3zR8m7PQuV5iDNDfYXfShnWBLUeVpdefuTs8mqh",
"time": "2019-11-06T17:38:55-08:00"
}
```
To be more specific, the bug seems to occur whenever the current local time is _before_ midnight, but the time in UTC is the next day _after_ midnight. When Mesh enters this state, no Ethereum RPC requests are allowed and Mesh cannot really function effectively.
> ethereum/ratelimit: Fix bug in for timezones behind UTC

- constants/constants.go
- core/core.go
- core/message_handler.go
- core/validation.go
- p2p/node.go
- p2p/ratevalidator/validator.go
- p2p/ratevalidator/validator_test.go
- zeroex/ordervalidator/order_validator.go
This PR addresses an oversight in `ratevalidator`. One of the goals of introducing a rate limiting validator for PubSub messages is to prevent other peers from using up _your_ bandwidth allotments when you propagate messages on their behalf. Before this PR, it was possible for a peer to send an extremely large message that would still get propagated (because we were propagating messages before checking the size). For well-behaving nodes, this PR doesn't change anything.
> p2p/ratevalidator: Enforce max message size

- CHANGELOG.md
I already updated the Releases page. It's probably okay if we don't retroactively make this change in older version tags, but we should at least correct it now on the `development` branch and any new releases going forward.
> Fix a link in the CHANGELOG

- core/core.go
- docs/deployment.md
I noticed that I had accidentally started my Kovan Mesh node with `BlockPollingInterval` set to `300ms` and `EthereumRPCMaxRequestsPer24HrUTC` defaulted to 100k requests. The math didn't add up and my node would definitively use up it's 24hr request limit and then stall. This PR does some math on Mesh startup to make sure these two configs won't eventually cause the Mesh node to malfunction due to using up all allowed requests for block polling alone.
> core,docs: Enforce reasonable configs for BlockPollingInterval and EthereumRPCMaxRequestsPer24HrUTC

- browser/.npmignore
- rpc/clients/typescript/.npmignore
We were missing an `.npmignore` in the TS Mesh RPC client package and the one in the browser package was too permissive (publishing the WASM bundle twice!).
> rpc,browser: Add & improve .npmignore

- Gopkg.lock
- Gopkg.toml
Hopefully this fixes the bug with `BandwidthCounter`. See https://github.com/libp2p/go-libp2p-core/issues/65. We'll need to deploy and then keep an eye on it for a while.
> Use a bugfix in go-flow-metrics.

- CHANGELOG.md
- core/core.go
New behavior: If order isn't new, e.g., we've already stored it, we avoid adding it to OrderWatcher again, triggering a log event and sharing it with peers once more.
> core: Fix bug of re-emitting receipt logs, re-sharing, re-adding duplicate orders

- .drone.yml
About
===
This PR adds a a Drone [0] CI configuration file which:
- Builds `latest` (if on `master`) and git-tagged based on `auto_tag` [1] which:
```
[...] will automatically tag the image using the standard major, minor, release convention. For example:
1.0.0 produces docker tags 1, 1.0, 1.0.0
1.0.0-rc.1 produces docker tags 1.0.0-rc.1
When the event type is push and the target branch is your default branch (e.g. master) the plugin will automatically tag the image as latest. All other event types and branches are ignored.
```
- Builds `development` branches tagged as `develop`
[0] - https://github.com/0xProject/0x-mesh/blob/master/CONTRIBUTING.md
[1] - http://plugins.drone.io/drone-plugins/drone-docker/
> Add Drone CI configuration file

- CHANGELOG.md
- browser/ts/index.ts
- rpc/clients/typescript/src/types.ts
This PR adds missing `UNEXPIRED` `OrderEventEndState` enum value to both `@0x/mesh-rpc-client` and `@0x/mesh-browser` and missing `STOPPED_WATCHING` value from `@0x/mesh-rpc-client`.
> rpc,browser: Add Missing OrderEventEndState enum values

- Gopkg.lock
- Gopkg.toml
- browser/package.json
- browser/ts/index.ts
- browser/yarn.lock
- db/open_js.go
- examples/browser/yarn.lock
- integration-tests/browser/yarn.lock
Fixes https://github.com/0xProject/0x-mesh/issues/532.
This PR adds support for persistence in browser environments. This is accomplished by using [BrowserFS](https://github.com/jvilk/BrowserFS) backed by [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API). The bulk of the work is actually in our fork of goleveldb, where we have [an open PR](https://github.com/syndtr/goleveldb/pull/288).
This solves the limitations of using localStorage as the backing for BrowserFS (limited to 10MB). This PR also includes code which will fallback to using an in-memory database if BrowserFS is not available. This is important because it allows us to continue to use `wasm-browser-test` for testing (`wasm-browser-test` does not offer any way to sideload JavaScript dependencies). …
> db, browser: Add support for persistence in the browser

- Gopkg.lock
- Gopkg.toml
- p2p/node.go
This is a potential solution to https://github.com/0xProject/0x-mesh/issues/452. Memory snapshots revealed that `go.opencensus.io/tag.(*Map).insert` was responsible for an unusually large amount of memory (up to 100MB after a few days). That package is used by `github.com/libp2p/go-libp2p-kad-dht`. https://github.com/libp2p/go-libp2p-kad-dht/issues/389 mentions this leak which was reported as fixed in version 0.2.1.
This PR updates `github.com/libp2p/go-libp2p-kad-dht` to the latest version. We will need to continue to monitor memory usage to see if this fixes the problem.
> Update go-libp2p-kad-dht to fix memory leak

- CHANGELOG.md
- loghooks/key_suffix_hook.go
Based on an issue reported on Discord. Though it doesn't happen often, `val` can sometimes be `nil`. Not handling this case explicitly results in a nil pointer exception.
> Fix a possible nil pointer exception in log hooks

- CHANGELOG.md
- cmd/mesh/rpc_handler.go
- rpc/service.go
Based on feedback from Discord. We were seeing the following log:
```
{"err_null":null,"level":"error","msg":"rpcSub returned an error","myPeerID":"16Uiu2HAm6PCaDbQscruxnGCUWgpxvX4RXqAUk3fGZy7CACCZ4Qpj","time":"2019-11-19T01:12:04Z"}
```
It is apparently possible to receive a value of `nil` from the `rpcSub.Err()` channel. This PR updates our code to handle that edge case.
> Handle nil errors from rpcSub.Err

- .drone.yml
This PR cherry picks the two commits from https://github.com/0xProject/0x-mesh/pull/525. That PR was merged into `master` instead of `development`.
> Add Drone CI configuration

- CHANGELOG.md
- cmd/mesh/main.go
- docs/deployment.md
There is currently a discrepancy in the documentation regarding the default RPC port. See https://0x-org.gitbook.io/mesh/v/v6.0.1-beta/getting-started/deployment.
In part of the documentation we claim:
> Ports 60557, 60558, and 60559 are the default ports used for the JSON RPC endpoint, communicating with peers over TCP, and communicating with peers over WebSockets, respectively.
However, later the documentation conflicts with this when the `RPC_ADDR` environment variable itself is documented:
>    // RPCAddr is the interface and port to use for the JSON-RPC API over
>    // WebSockets. By default, 0x Mesh will listen on localhost and will let the
>    // OS select a randomly available port.
>    RPCAddr string `envvar:"RPC_ADDR" default:"localhost:0"`
In version `6.0.1-beta`, Mesh …
> Set default RPC port to 60557

- CHANGELOG.md
- cmd/mesh/rpc_handler.go
Until now, if an RPC request caused a panic, the panic was caught by the `go-ethereum` rpc library and a non-descript `method handler crashed` error message was returned to the caller. In order to log a helpful error message, including the stack trace of where the panic originated from, this PR adds panic recovery to all methods in RPCHandler.
> rpc: log errors when RPC method panics

- CHANGELOG.md
- constants/constants.go
- core/core.go
- ethereum/blockwatch/block_watcher.go
- ethereum/blockwatch/block_watcher_test.go
- ethereum/blockwatch/simple_stack.go
- ethereum/blockwatch/testdata/fake_client_fast_sync_fixture.json
- ethereum/blockwatch/testdata/fake_client_reset_fixture.json
- ethereum/dbstack/db_stack.go
- meshdb/meshdb.go
- zeroex/orderwatch/order_watcher.go
Fixes: https://github.com/0xProject/0x-mesh/issues/470 and https://github.com/0xProject/0x-mesh/issues/407
New logic is:
- If less than 128 blocks elapsed, fast-sync block events
- If more than 128 blocks, re-set stored blocks in DB and re-validate all stored orders.
> core,blockwatch: Limit fast-sync to last 128 blocks

- CHANGELOG.md
- cmd/mesh/rpc_handler.go
- rpc/service.go
Fixes a possible bug where failing to unsubscribe from the order events feed can cause Mesh to hang.
> Always unsubscribe from order events in SetupOrderStream

- CHANGELOG.md
- cmd/mesh/rpc_handler.go
- rpc/service.go
Reverts 0xProject/0x-mesh#552. We accidentally merged to master instead of development.
> Revert "Always unsubscribe from order events in SetupOrderStream"

- CHANGELOG.md
- core/core.go
- ethereum/blockwatch/block_watcher.go
Fixes #558.
As far as I can tell there is only one case where a field may not be fully initialized which can result in a nil pointer exception. All the issues we were seeing stem from this. The problem is that `app.node` is nil before `app.Start` is called (and sort of has to be because of how the libp2p works).
This PR fixes the issue by using a `started` channel inside of `core.App` to signal when `app.node` has been initialized. Any methods that depend on `app.node` will block by waiting to receive on the `app.started` channel. This can be easily extended to support other edge cases for any fields cannot be initialized until after `Start` is called.
> Block as needed inside core.App until started

- cmd/mesh/rpc_handler.go
This should really be logged as errors but we were previously using `Printf` which results in the log level "Info".
> Log recoveries from RPC method crashes as errors

- CHANGELOG.md
- zeroex/order.go
- zeroex/order_js.go
Previously, a null `makerAssetFeeData` or `takerAssetFeeData` was being encoded as an empty string, which is incorrect.
> Handle null fee asset data in browser bindings

- CHANGELOG.md
- browser/go/main.go
- browser/ts/index.ts
- core/core.go
- docs/deployment.md
- ethereum/ratelimit/fake_rate_limiter.go
- zeroex/ordervalidator/order_validator_test.go
- zeroex/orderwatch/order_watcher_test.go
This new environment variable will allow users to completely disable Ethereum RPC rate limiting. Disabling the feature does come with some risks and can lead to abnormally high bills for services like Infura and Alchemy depending on network conditions. Still, some users, and in particular market makers, might prefer higher costs to the alternative of not receiving order updates quickly.
> Add new ENABLE_ETHEREUM_RPC_RATE_LIMITING environment variable

- zeroex/orderwatch/order_watcher.go
See https://github.com/0xProject/0x-mesh/issues/583. The nil pointer exception appears to be occurring because `validationResults` contains an order but that order's hash is not found in `orderHashToDBOrder`.
I took a look at the code path, and I couldn't determine why this might be the case. This PR doesn't fix the underlying issue, but it does log the order hash and stop us from panicking which can help us understand what's going on.
> Log error when validationResults contains unknown order hash

- CHANGELOG.md
- browser/ts/index.ts
- core/core.go
- docs/deployment.md
- ethereum/ratelimit/rate_limiter.go
- ethereum/ratelimit/rate_limiter_test.go
This PR simplifies our implementation of Ethereum RPC rate limiting in order to address some potential bugs and make it easier to test. In general, it also loosens the restrictions of the rate limiter to make it less likely to affect non-spammers under normal network conditions.
This is most likely a fix for #585.
Summary of changes:
1. Removed the `rate.Limiter` that was used to enforce `ETHEREUM_RPC_MAX_REQUESTS_PER_24_HR_UTC`. This limit is now enforced via a simple counter which is reset every UTC midnight. This greatly simplifies our implementation and makes it easier to write tests. It also reduces the chances of artificially limiting the rate of requests for non-spammers (especially around UTC midnight). But it does come with the downside of not guaranteeing that RPC requests will …
> Simplify Ethereum RPC rate limiting

- CHANGELOG.md
- rpc/clients/typescript/package.json
- rpc/clients/typescript/src/types.ts
- rpc/clients/typescript/src/ws_client.ts
- rpc/clients/typescript/test/ws_client_test.ts
- rpc/clients/typescript/yarn.lock
Our changes have been merged upstream: https://github.com/ethereum/web3.js/pull/2994/files albeit with slightly different naming.
The upstream version includes bug fixes our users are running into.
> rpc: Move off our fork of web3-providers in Mesh RPC Client

- CHANGELOG.md
- rpc/clients/typescript/src/ws_client.ts
Fixes: https://github.com/0xProject/0x-mesh/issues/600
Currently if one instantiates a `WSClient` without supplying a custom `wsOpts` param, the client defaults to not having a timeout length on the RPC requests it sends. This is problematic, because during network disruptions, it is possible for the client to miss a response and hang forever. Because of this, we are changing the default to include a 30sec timeout on all non-subscription RPC requests.
> rpc: Add RPC request timeout to default wsOpts

- CHANGELOG.md
- browser/ts/index.ts
- integration-tests/rpc_integration_test.go
- rpc/clients/typescript/src/types.ts
- rpc/clients/typescript/src/ws_client.ts
- rpc/clients/typescript/test/ws_client_test.ts
- zeroex/order.go
- zeroex/order_test.go
- zeroex/orderwatch/order_watcher.go
Fixes: #557 
For Mesh-specific events, we use the current UTC time. For on-chain state triggered events, we use the block height at which the order was re-validated.
> zeroex,rpc,browser: Add Timestamp to OrderEvents

- integration-tests/rpc_integration_test.go
Fix test so doesn't doesn't depend on the version being `development`which it isn't when we create a release PR.
> integration-tests: Stop checking version returned from `mesh_getStats`

- CHANGELOG.md
- ethereum/blockchain_lifecycle.go
- zeroex/orderwatch/order_watcher.go
Fixes: https://github.com/0xProject/0x-mesh/issues/608
Currently it is possible that we attempt to update orders that expire or unexpire twice within the same txn. This causes the second update to noop since our DB txns do not support multiple updates within a single txn. This PR stops this from happening.
> orderwatch: Avoid updating orders multiple times in same txn (part 2)

- CHANGELOG.md
- constants/constants.go
- core/message_handler.go
- core/validation.go
- p2p/node.go
- p2p/ratevalidator/validator.go
- p2p/ratevalidator/validator_test.go
- zeroex/orderwatch/order_watcher.go
Fixes #615.
This PR increases the maximum order size to 16k bytes. It also introduces a separate limit called `MaxMessageSizeInBytes` and a corresponding error `ErrMaxMessageSize`. Previously we were conflating these two limits, but they should technically be different.
> Increase max order size and create separate max message size

- CHANGELOG.md
- db/transaction.go
- db/transaction_test.go
- zeroex/orderwatch/order_watcher.go
- zeroex/orderwatch/order_watcher_test.go
> orderwatch: Avoid conflicting txn error when updating block headers in DB

- CHANGELOG.md
- core/core.go
- ethereum/contract_addresses.go
Several developers have been slowed down by having to wait until a smart contract fix be officially included in Mesh. This PR allows them to point their Mesh node to the fixed smart contract on testnets while still guarding mainnet contracts from being swapped out.
> core,ethereum: Allow testnet contract addressses override

- dockerfiles/mesh-bootstrap/Dockerfile
- dockerfiles/mesh/Dockerfile
Our migration to Go Modules (https://github.com/0xProject/0x-mesh/pull/618) broke our `dockerfile`'s dep installation step. This PR fixes it.
> dockerfile: Fix dep install step

- CHANGELOG.md
- rpc/clients/typescript/src/ws_client.ts
- rpc/clients/typescript/test/ws_client_test.ts
> rpc,typescript: Add Paginated getOrders method

- dockerfiles/mesh-bootstrap/Dockerfile
- dockerfiles/mesh/Dockerfile
Prior to this PR, trying to build either the `mesh` or `mesh-bootstrap` images results in the following error:
```
db/batch.go:6:2: cannot find package "github.com/syndtr/goleveldb/leveldb/opt" in any of:
/usr/local/go/src/github.com/syndtr/goleveldb/leveldb/opt (from $GOROOT)
/go/src/github.com/syndtr/goleveldb/leveldb/opt (from $GOPATH)
db/batch.go:7:2: cannot find package "github.com/syndtr/goleveldb/leveldb/util" in any of:
/usr/local/go/src/github.com/syndtr/goleveldb/leveldb/util (from $GOROOT)
/go/src/github.com/syndtr/goleveldb/leveldb/util (from $GOPATH)
core/core.go:42:2: cannot find package "github.com/xeipuuv/gojsonschema" in any of:
/usr/local/go/src/github.com/xeipuuv/gojsonschema (from $GOROOT)
/go/src/github.com/xeipuuv/gojsonschema (from $GOPATH) …
```
> Change dockerfiles to build outside of GOPATH

- CHANGELOG.md
- go.mod
- go.sum
In https://github.com/0xProject/0x-mesh/pull/539 we upgraded `github.com/libp2p/go-libp2p-kad-dht` to fix a memory leak. It looks like we regressed as part of the switch to Go Modules and an older version of the package was re-introduced. This PR fixes the problem by explicitly specifying version 0.3.0.
> Upgrade kad-dht to 0.3.0 to fix a regression

- CHANGELOG.md
- browser/go/main.go
- browser/ts/index.ts
- common/types/types_js.go
- integration-tests/browser/src/index.ts
Fixes #576. This PR implements `getStatsAsync` for browsers.
Based on the `fix/no-rpc-in-core` branch. We need to merge #653 before this one.
> Implement getStatsAsync for browsers

- CHANGELOG.md
- browser/go/main.go
- browser/ts/index.ts
- common/types/types_js.go
- integration-tests/browser/src/index.ts
Fixes #577. This PR adds both `getOrdersAsync` and `getOrdersForPageAsync` to the `@0x/mesh-browser` package.
> Implement getOrdersAsync getOrdersForPageAsync for browsers

- go.sum
- zeroex/order.go
- zeroex/order_js.go
- zeroex/orderwatch/decoder/event_decoder.go
- zeroex/orderwatch/decoder/event_decoder_js.go
- zeroex/orderwatch/decoder/event_decoder_test.go
This PR patches a known issue in the `OrderEvent` `js.Value` encoding logic and fixes #656.
> Patched bugs in js.Value conversion logic

- go.mod
- go.sum
Similar to https://github.com/0xProject/0x-mesh/pull/650, there was another regression that occurred when we made the switch to Go Modules. Hard-coding the version for `go-flow-metrics` in the `replace` section fixes the issue.
The original fix was here: https://github.com/0xProject/0x-mesh/pull/521. The result of this regression is false positives in the bandwidth limiter (see also https://github.com/libp2p/go-libp2p-core/issues/65 for more info about the false positives).
> Override go-flow-metrics version to fix a regression

- ethereum/ratelimit/rate_limiter_test.go
I was still noticing some CI failures due to timing differences, especially when running tests in a headless browser. You can find a recent example here: https://app.circleci.com/jobs/github/0xProject/0x-mesh/2515.
> Increase timing tolerance in rate_limiter_test.go

- CHANGELOG.md
- browser/go/ethprovider/ethprovider.go
- browser/go/jsutil/jsutil.go
- browser/go/main.go
- browser/go/providerwrapper/providerwrapper.go
- browser/package.json
- browser/ts/index.ts
- core/core.go
- ethereum/ethrpcclient/eth_rpc_client.go
- examples/browser/src/index.ts
- examples/browser/yarn.lock
- go.mod
- go.sum
- integration-tests/browser/src/index.ts
- integration-tests/browser/yarn.lock
- zeroex/ordervalidator/order_validator_test.go
- zeroex/orderwatch/order_watcher_test.go
Fixes #581.
This PR adds the ability to use a Web3 Provider in the browser, which takes the place of `config.EthereumRPCURL` and will be used for all Ethereum RPC requests.
Most of the magic is in the new `providerwrapper` package. This package implements `ethclient.RPCClient` by wrapping a Web3 provider and calling `sendAsync`.
I also updated the integration tests to use a Web3 Provider. This is the bare minimum we can do for testing. After https://github.com/0xProject/0x-mesh/pull/649 is merged we should plan on adding more unit tests for a lot of the conversion code in this PR.
This PR depends on some changes to two separate dependencies:
1. For `go-ethereum`, I [refactored `ethclient.RPCClient` into an interface](https://github.com/0xProject/go-ethereum/commits/wasm_signer_core_3).
2. …
> Add support for passing in a Web3 Provider in the browser

- .circleci/config.yml
- CONTRIBUTING.md
- browser/ts/wasm_exec.ts
- core/message_handler_test.go
- dockerfiles/mesh-bootstrap/Dockerfile
- dockerfiles/mesh/Dockerfile
- go.mod
- integration-tests/utils.go
- zeroex/ordervalidator/order_validator_test.go
- zeroex/orderwatch/order_watcher_test.go
Fixes #480. This will help us include some small but important optimizations (especially in the browser) and keep up with the Go ecosystem. libp2p has already switched to 1.13.
> Upgrade to Go 1.13

- .drone.yml
About
===
Current `drone` configuration incorrectly builds and tags `mesh-bootstrap` images, it uses the `dockerfiles/mesh/Dockerfile` instead of `dockerfiles/mesh-bootstrap/Dockerfile`.
This PR fixes that.
> Fix mesh-bootstrap drone config to point to the correct Dockerfile.

- core/core.go
So far, this hasn't really come up, but there's a small bug in `core.New`. If it's called multiple times in the same process (e.g. in a test) it will initialize the logger twice. This results in double type suffixes and `myPeerID` appearing in the logs twice for each log message. Using `sync.Once` fixes the issue.
> Only set up logger once in core.New

- .circleci/config.yml
- CHANGELOG.md
- core/core.go
- db/transaction.go
- db/transaction_test.go
- ethereum/blockchain_lifecycle.go
- ethereum/contract_addresses.go
- rpc/clients/typescript/src/ws_client.ts
- zeroex/orderwatch/order_watcher.go
- zeroex/orderwatch/order_watcher_test.go
This backports a bunch of recent fixes needed by TokenTrove who is still running a 0x V2 node alongside their 0x V3 node. See CHANGELOG entry for full list.
> Backport Release 7.1.0-beta

- zeroex/orderwatch/order_watcher.go
This PR fixes a small bug in the order watcher cleanup loop that prevents `core.App` from properly shutting down when the main context is canceled. Namely, the old version of the cleanup loop had a `time.Sleep` statement that existed outside of `select`. So if the context was canceled, we would still wait for `time.Sleep` to finish. This was causing difficulties in understanding test failures on #692.
> Make order watcher exit as soon as context is canceled

- zeroex/orderwatch/order_watcher.go
- zeroex/orderwatch/order_watcher_test.go
I discovered this inefficiency while bench-marking the performance of the OrderWatcher. It is  possible that multiple blockEvents are queued up within the `blockEventsChan` and we _could_ process them all at once but weren't. It is possible that the events in these array would lead to the same order being re-validated, and so combining them leads to fewer RPC calls and lowers the latency after which we emit relevant order events.
> orderwatch: Batch process multiple block event arrays at once

- .drone.yml
- cmd/cut-release/main.go
This PR:
- Adds to our `cut-release` script a step to generate a `RELEASE_CHANGELOG.md` file containing the contents of the release notes for this release.
- Adds a Drone job that executes when a Git release tag is pushed to our repo, and publishes the new release notes to Github.
> chore: Automate Release Notes Generation

- go.mod
- go.sum
- p2p/bootstrap.go
- p2p/opts.go
This PR adds support for dialing and advertising WSS addresses. It does not add support for listening directly on WSS, however that can be accomplished via a simple proxy.
Currently we are relying on our fork of `libp2p/go-ws-transport`, which adds support for WSS. See https://github.com/libp2p/go-ws-transport/pull/72. We might be able to use the upstream version depending on timing.
I also manually tested that Mesh works in the browser on HTTPS URLs by using [ngrok](https://dashboard.ngrok.com/get-started). 
With help from @opaolini we manually upgraded one relay node to support WSS addresses and confirmed that two browser peers on HTTPS were able to use it to connect to each other.
> Add support for WSS

- CHANGELOG.md
- cmd/mesh/main.go
- cmd/mesh/rpc_handler.go
- dockerfiles/mesh/Dockerfile
- docs/deployment.md
- docs/deployment_with_telemetry.md
- examples/go/README.md
- examples/go/add-order/main.go
- examples/go/subscribe-to-orders/main.go
- integration-tests/browser_integration_test.go
- integration-tests/constants.go
- integration-tests/rpc_integration_test.go
- integration-tests/utils.go
- rpc/clients/typescript/test/utils/ws_server.ts
- rpc/server.go
Fixes: https://github.com/0xProject/0x-mesh/issues/122
> rpc: Add HTTP JSON-RPC Support

- CHANGELOG.md
- browser/ts/index.ts
- zeroex/order_js.go
Squashes some bugs in the browser Typescript bindings and in the Go to Javascript conversion functions.
> Addressed inconsistencies in the Typescript bindings in the browser

- cmd/mesh-bootstrap/main.go
About
===
This PR adds a `UseBootstrapList` flag to `mesh-bootstrap` config in order to have an easy way to prevent the `mesh-bootstrap` from connecting to the `DefaultBootstrapList`.
> Add UseBootstrapList flag to mesh-bootstrap config

- core/core.go
Normally on startup, we do a sanity check for `BLOCK_POLLING_INTERVAL` and `ETHEREUM_RPC_MAX_REQUESTS_PER_24_HR_UTC`. We don't need to do this if Ethereum RPC rate limiting is disabled via `ENABLE_ETHEREUM_RPC_RATE_LIMITING`
> Skip unnecessary check if ETH RPC rate limiting is disabled

- ethereum/ratelimit/rate_limiter.go
This should fix a [race condition that sometimes shows up in CI](https://app.circleci.com/jobs/github/0xProject/0x-mesh/2653). `wg.Add` should be called outside of the goroutine.
> Fix a race condition in ethereum/ratelimit

- Makefile
- browser/conversion-tests/conversion_test.ts
- browser/go/browserutil/browserutil.go
- browser/go/conversion-test/conversion_test.go
- browser/go/conversion-test/main.go
- browser/go/mesh-browser/main.go
- browser/package.json
- browser/webpack.config.js
- browser/yarn.lock
Added tests for the `convertConfig` function that use the new framework.
> convertConfig Tests

- .drone.yml
Fix drone build failure by using a glob instead of a directory for the "files" field.
Docs: http://plugins.drone.io/drone-plugins/drone-github-release/
> drone: Fix Github release artifacts

- CHANGELOG.md
- core/core.go
- meshdb/meshdb.go
- meshdb/meshdb_test.go
- zeroex/orderwatch/order_watcher.go
- zeroex/orderwatch/order_watcher_test.go
Fixes: #667 
It also makes sure we delete miniHeaders from the DB after processing new block events that could cause new miniHeaders to be added to the DB, such that the number of miniHeaders stored does not exceed the retention limit.
> Remove MiniHeaders above retention limit on startup & after processing block events

- p2p/opts_js.go
We have more performance headroom since implementing #692. Increasing the max number of peers will help each node find the right peers (e.g. those using the same topic) faster and make the network healthier in general. Of course, there is still room for further improvement for finding the right peers faster (see #582).
> Increase maximum peers for browser nodes

- .drone.yml
Drone is broken because of a previous misguided fix.
> drone: Fix Github Release task

- core/core.go
- meshdb/meshdb.go
Previously we were logging this warning every time we removed miniheaders from the database, which is not necessary. We only need to warn when there are extra miniheaders in the database _on startup_, since that is not expected.
> Only log warning about outdated miniheaders on startup

- .circleci/config.yml
- Makefile
We should be running the TypeScript tests as part of `make test-all`. I think the fact that we weren't previously was just an oversight.
> Run TypeScript tests as part of make test-all

- ethereum/blockwatch/block_watcher.go
- ethereum/blockwatch/block_watcher_test.go
"I think it would be amazing if every log that has an error level indicates a bug that we need to fix."
-- @jalextowle 
Towards that aim, this PR demotes the recoverable errors returned from blockwatch to warnings. Most are unavoidable and not things we can fix so it doesn't make sense to consider them errors given the above definition. To reduce the clutter, it makes sense to demote them.
> blockwatch: Demote blockwatcher recoverable errors to warnings

- CHANGELOG.md
- common/types/types.go
- common/types/types_js.go
- core/core.go
- integration-tests/rpc_integration_test.go
- orderfilter/filter.go
- p2p/node.go
- p2p/node_test.go
- packages/browser-lite/src/types.ts
- packages/browser/conversion-tests/conversion_test.ts
- packages/browser/go/conversion-test/conversion_test.go
- packages/browser/go/conversion-test/main.go
- packages/rpc-client/test/ws_client_test.ts
- yarn.lock
Fixes #582.
This PR includes a handful of related changes which improve peer discovery, especially for those using custom order filters. In general this will make the process of finding new peers, and specifically finding the _right_ peers, much faster.
1. Created separate rendezvous points for peers using custom order filters.
2. Made peer discovery parallel so it doesn't block message handling.
3. Connect to peers on the rendezvous points before advertising ourselves.
> Improve peer discovery

- CHANGELOG.md
- go.mod
- go.sum
Possible fix for #551. This PR updates Mesh to use a custom fork of `libp2p/go-libp2p-pubsub`, which increases the size of the channel for incoming messages from 32 to 1000. This fixes an issue reported by Augur where orders were sometimes not being received by peers in stress testing/benchmarking scenarios. The same issue could also be encountered in the real world, although it is less likely since #692.
See also https://github.com/libp2p/go-libp2p-pubsub/issues/217 which mentions the small queue sizes and other related issues.
> Use our fork of pubsub which increases queue size

- core/core.go
It looks like a Git auto-merge created a compiler error, which unfortunately CI was not able to detect. This is a pretty rare case but if it happens more often we could look into tweaking CI so that it simulates a merge before running the tests.
> Fix compiler error in core.go

- cmd/mesh/main.go
- cmd/mesh/rpc_handler.go
- integration-tests/browser_integration_test.go
- integration-tests/rpc_integration_test.go
- packages/rpc-client/test/utils/ws_server.ts
The `rpc_integration_test` would intermittently fail because the HTTP and WebSocket RPC Servers would log the same message when they started. The tests were designed with only one RPC server in mind, and this meant that there was a race-condition in the tests.
> Improved RPC Server Initialization Log 

- cmd/cut-release/main.go
- packages/browser-lite/README.md
- Delete `typedoc-tsconfig.json:qw`
- Refactors `cut-release` to use the top-level `yarn docs:md` command.
- Improved `@0x/mesh-browser-lite` README.md
> Post `v9.1.0` cleanup

- cmd/mesh-bootstrap/main.go
- p2p/node.go
Since https://github.com/0xProject/0x-mesh/pull/692 was implemented we have been seeing vastly reduced bandwidth usage. We can now safely reduce the per-IP bandwidth limits.
> Decrease max bytes/s from 100 MiB to 1 MiB

- CHANGELOG.md
- zeroex/orderwatch/order_watcher.go
This PR solves one of the main performance bottlenecks for order propagation speed, especially when adding many orders at once. Prior to this PR, `orderwatch.Watcher.add` only accepted one order at a time. This PR updates it to accept multiple orders in an array, which means we can add all of them in a single database transaction.
One side-effect of this PR is that it is slightly more likely to end up with more than `MAX_ORDERS_IN_STORAGE` in storage temporarily. The chance of that happening is still slim, it would never exceed the maximum batch size, and would quickly be corrected. I think this trade-off is worth it.
> Support adding multiple orders to Watcher.add in a single batch.

- CHANGELOG.md
- core/ordersync_subprotocols.go
This PR fixes a critical bug in the `FilteredPaginationSubProtocol` for ordersync. There was an off-by-one error in the for loop where we were incrementing `currentPage` _before_ checking for the end condition in each iteration of the loop. This caused every other page to be skipped, resulting in around 50% of the orders actually being shared.
I wanted to create a regression test as part of this PR but doing so has proven difficult. We need to create at least `paginationSubprotocolPerPage * 2 + 1` orders in order to see this bug in the tests. This has proven difficult for two reasons:
1. Since `paginationSubprotocolPerPage` is not configurable via an environment variable, we are stuck with the default value of 500. We don't want to make it configurable as it is too easy for users of Mesh …
> Fix a bug in the ordersync pagination subprotocol

- core/core.go
- core/ordersync/ordersync.go
- core/ordersync/ordersync_test.go
This PR adds a new method to the ordersync service called `PeriodicallyGetOrders` which simply calls `GetOrders` on a regular interval (~~currently set to 5 minutes~~). Update: now set to 1 hour. See [comment below](https://github.com/0xProject/0x-mesh/pull/764#issuecomment-601440504).
This accounts for situations where we receive an order which is not valid now but may be valid in the future. There are a couple scenarios where this could happen. Here's just a few examples:
1. A block re-org causes filled or cancelled orders to be fillable again. While we do account for this kind of re-org by marking existing orders as removed before we ultimately delete them from the database, that doesn't account for orders that were unfillable _the first time_ we saw them. Those orders are currently …
> Periodically rerun ordersync instead of running it only once on startup

- CHANGELOG.md
- packages/browser-lite/src/index.ts
This PR fixes a compatibility issue with Safari (and other browsers that don't support `isntantiateStreaming`). When `instantiateStreaming` is not supported, we fallback to `instantiate`.
> Add a polyfill for WebAssembly.instantateStreaming

- CHANGELOG.md
- core/core.go
- core/core_test.go
- core/eth_rpc_chain_id.go
> Compare chain id env variable with rpc on startup

- cmd/cut-release/main.go
- packages/browser-lite/src/types.ts
- packages/browser-lite/src/wasm_exec.ts
- packages/browser-lite/src/wrapper_conversion.ts
Currently document generation is a somewhat manual process because of the fact that we generate docs for all exported fields (even if they aren't exported at the package level) and because TypeDoc `v0.15.0` does not document functions. This PR fixes this by adding a small script to `cut-release`.
```
git checkout docs/automate-doc-generation
VERSION=100.0.0 go run cmd/cut-release/main.go
behold "the glory of automated doc generation"
```
> Fully Automate Document Generation

- CHANGELOG.md
- expirationwatch/expiration_watcher.go
- expirationwatch/expiration_watcher_test.go
An order becomes expired when `order.expirationTimeSeconds <= block.timestamp` ([source](https://github.com/0xProject/0x-monorepo/blob/development/contracts/exchange/contracts/src/MixinExchangeCore.sol#L171)). Previously, Mesh pruned orders once `timestamp.After(expirationTime) == true`, which would allow `GetOrders` to return invalid orders when `timestamp == expirationTime`.
Big thanks to @dekz for reporting the bug!
> [expirationwatch] Fixes consistency bug

- zeroex/orderwatch/order_watcher_test.go
Fixes a race condition in one of the `orderwatcher` tests between funding an order and validating it. The fix was taken from `integration-tests`. It does not appear that any other test cases in `zeroex/orderwatcher/order_watcher_test.go` are affected by this race condition because they all include at least one contract call prior to calling `syncToLatestBlock`.
> [zeroex/orderwatch] Fixed race-condition in test

- scenario/scenario.go
- zeroex/orderwatch/order_watcher.go
- zeroex/orderwatch/order_watcher_test.go
This PR changes order watcher so that we revalidate any affected orders for ERC721 approval events regardless of the operator address. Previously, we only considered events where the operator was the ERC721Proxy.
Because of the way the ERC721 spec works, when using `Approve`, you can only have one operator for each token ID (this is independent from "account operators" which can be set via `SetApprovalForAll`). If a user sets the operator to a different address, that could mean that the ERC721Proxy no longer has approval, in which case we need to revalidate any affected orders.
This PR also updates the `scenario` package to approve individual ERC721 tokens when possible.
> Revalidate affected orders regardless of ERC721 approval operator

- integration-tests/rpc_integration_test.go
- scenario/scenario.go
- zeroex/orderwatch/order_watcher_test.go
This PR is a follow-up on #779 and adds support for creating more than one order in a single batch via the `NewSignedTestOrdersBatch` function. This is a huge performance optimization because we only set the required balances and allowances once instead of doing it (and waiting for the corresponding transaction to be mined) for each order one at a time. This is not just optimization for the sake of optimization; it will enable important new test cases by making it practical to create hundreds of orders at a time (see https://github.com/0xProject/0x-mesh/pull/760 for an example of how this limitation has blocked us in the past).
> scenario: Add ability to create multiple orders in a single batch

- p2p/node.go
This is a quick and easy optimization to prevent us from spending time processing an empty batch of orders. Prior to this PR, we would perform a small amount of computational work (including logging and acquiring some locks) even if there were no orders to validate.
> p2p: Don't call HandleMessages if there are no messages to handle

- core/core.go
- core/core_test.go
- core/ordersync/ordersync.go
Fixes #761. Also fixes a minor bug where the exponential backoff for ordersync was too long in some circumstances.
> Add missing regression test for ordersync pagination subprotocol

- .circleci/config.yml
- Makefile
I think this organization is a little more intuitive. `make test-go` should only run pure Go tests, not anything having to do with Wasm or JavaScript.
> Move browser-conversion-tests out of make test-go

- packages/browser-lite/package.json
- packages/browser-lite/src/schema_validator.ts
- yarn.lock
- Hides the `schema_validator` module so that our documentation does not include these un-exported (from `index.ts`) types and functions.
- Removes the `@0x/contract-addresses` dependency from `@0x/mesh-browser-lite`.
> Post v9.4.0 Cleanup

- orderfilter/filter_bench_test.go
This PR adds a benchmark for `orderfilter.ValidateOrder`. I used this benchmark to confirm that https://github.com/0xProject/0x-mesh/pull/809 does have a positive impact on performance. We should add more benchmarks as needed over time.
Run the benchmark with the following comands:
```bash
go test ./orderfilter --bench . --run NONE
WASM_INIT_FILE="$(pwd)/packages/test-wasm/dist/browser_shim.js" GOOS=js GOARCH=wasm go test -exec="wasmbrowsertest" ./orderfilter -bench . -run NONE
```
Here are the results for native Go:
```
goos: darwin
goarch: amd64
pkg: github.com/0xProject/0x-mesh/orderfilter
BenchmarkMatchOrder-16    	   21661	     54750 ns/op
PASS
```
Wasm/JS prior to https://github.com/0xProject/0x-mesh/pull/809:
```
goos: js
goarch: wasm
pkg: github.com/0xProject/0x-mesh/orderfilter …
```
> Add benchmark for ValidateOrder

- packages/browser-lite/src/database.ts
This PR fixes an occasional bug that has to do with Dexie/IndexedDB and transactions. Dexie tries to re-use underlying IndexedDB transactions when possible under the hood, and [according to the documentation this feature is supposed to work with TypeScript and transpilation](https://dexie.org/docs/Dexie/Dexie.transaction()). Whether it is something with our exact TypeScript/Webpack setup, how Go runs JavaScript functions as part of its WebAssembly runtime, or simply a bug in Dexie, the re-use of transactions seems to sometimes get out of whack. The issue usually surfaces as an error that looks like this:
```
Failed to execute 'objectStore' on 'IDBTransaction': The specified object store was not found.
```
However it sometimes also manifests as other error messages, which always have …
> Add workaround for Dexie transaction-related errors

- ethereum/ratelimit/rate_limiter_test.go
Increases the tolerance in the `ratelimit` tests. This should fix an intermittent issue that we have seen on CI.
> Increased the `ratelimiter` tolerance

- tsconfig-base.json
ES2016 was selected by starting with browsers that support WebAssembly and choosing the latest ECMAScript version that does not exclude any of those. The browsers that were considered for compatibility are: Chrome, Firefox, Safari, and Edge. Mesh is not compatible with Internet Explorer because it does not support WebAssembly. We cannot target ES2017 because not all features are supported by Firefox and Safari.
- [Which browsers support WebAssembly](https://caniuse.com/#feat=wasm)
- [Which browsers support ES2016+ features](http://kangax.github.io/compat-table/es2016plus/)
> Update TypeScript compiler target to ES2016

- go.mod
- zeroex/orderwatch/order_watcher.go
Before this, `permanentlyDeleteStaleRemovedOrders` runs once each `minRemovedCheckInterval`. With this change, we will check if the database utilization rates exceeds `databaseUtilizationThreshold` each `countInterval` and run `permanentlyDeleteStaleRemovedOrders` if so. Additionally, if `permanentlyDeleteStaleRemovedOrders` hasn't been run within the last `maxDeleteInterval`, we will run it.
> Update removedChecker to use countInterval

- Makefile
- core/ordersync/ordersync.go
This PR addresses one of the lowest hanging pieces of fruit in `ordersync`. Previously, the `GetOrders` function would try to get orders from peers one at a time. This was easy to understand, but was also suboptimal from a performance perspective. This PR makes changes that allows this function to request orders from multiple peers at once.
> Parallelize requesting from peers in `ordersync`

- go.mod
- zeroex/orderwatch/order_watcher.go
- zeroex/orderwatch/order_watcher_test.go
> Use errgroup

- zeroex/orderwatch/order_watcher.go
> Simplify unexpiration logic in convertValidationResultsIntoOrderEvents

- db/sql_implementation.go
- db/sqltypes/sqltypes.go
This PR addresses the occasional `database is locked` errors that can occur when using SQLite on some platforms. See https://github.com/mattn/go-sqlite3/issues/607 and https://github.com/mattn/go-sqlite3/pull/827 for some more information. The fix involves adding a `sync.RWMutex` to __/db/sql_implementation.go__. I also moved some code around to try and hold on to the mutex for as little time as possible for each method.
> Fix database is locked error

- core/core.go
- core/core_test.go
- core/ordersync/ordersync.go
Partially Addresses: #871 
This PR fixes two issues:
* Ordersync sub-protocols previously considered a sync that yielded 0 orders in total a success. This was a bug, and was resolved by this PR.
* A subtle issue that was introduced by #848. Because the parallelized version of ordersync would connect to several peers and would cancel the context when we had synced with a sufficient number of extra peers, it was possible for the response of several peers with a small amount of orders to short-circuit ordersync runs with other peers that had more orders. This would lead to the node not always getting all of the orders during ordersync.
After this PR, we will only make as many parallel requests as can actually be resolved without going over `ordersyncMinPeers`. Future PRs should refine the …
> fix: Wait for high quality peers to fully respond during ordersync

- core/ordersync/ordersync.go
- core/ordersync_subprotocols.go
Prior to this PR, a sync would be marked as a success provided that there was a nonzero number of orders returned in an ordersync response. Upon closer inspection, this was not strict enough since these orders may not pass the `orderfilter`. In this PR, we addressed the issue by keeping track of how many orders that match the filter have been contributed by a given ordersync peer.
> fix: Mark an ordersync that yields zero orders unsuccessful

- core/core.go
- db/common.go
- ethereum/blockwatch/block_watcher.go
- zeroex/orderwatch/order_watcher.go
- zeroex/orderwatch/order_watcher_test.go
Fixes: #590 
This PR addresses an issue in the current implementation of the orderwatcher that allows some block events to be missed when an `eth_call` to `DevUtils` for order validation starts before the blockwatcher finishes syncing and resolves after the `handleBlockEvents` function has been called. Instead of using a database lock, the mechanism implemented in this PR will double check that recently validated orders are valid at the tip of the canonical chain. This should be a more performant patch than simply locking the database whenever new blocks are being synced in the blockwatcher.
> Address the missing order events edge case

- core/ordersync/ordersync.go
> Added the ability to track the progress of ordersyncing with peers

- db/common.go
- db/db_test.go
- db/dexie_implementation.go
- db/sql_implementation.go
- packages/mesh-browser-lite/src/database.ts
- zeroex/orderwatch/order_watcher.go
This PR optimizes how we check for already stored orders in `meshSpecificOrderValidation`. It introduces a new database method, `GetOrderStatuses` which accepts an array of order hashes and checks each one.
It also adds some new log messages to identify slow queries. This can help point us toward future areas of improvement.
> Check for already stored orders in a single batch

- cmd/mesh-bootstrap/main.go
- core/core.go
- p2p/node.go
- packages/mesh-browser-lite/src/types.ts
- packages/mesh-browser/conversion-tests/conversion_test.ts
- packages/mesh-browser/go/browserutil/browserutil.go
- packages/mesh-browser/go/conversion-test/main.go
> Made `MaxBytesPerSecond` configurable for standalone nodes

- core/core.go
This is a small fix which changes the logic for when we check for missing order events.
> Don't check for missing events if no blocks have elapsed

- db/common.go
- db/db_test.go
- db/dexie_implementation.go
- db/sql_implementation.go
- packages/mesh-browser-lite/src/database.ts
- zeroex/orderwatch/order_watcher.go
This PR fixes a subtle bug in orderwatcher.
We call `DB.AddOrders` and assume that any order which does not appear in either `added` or `removed` was not added because its expiration time was too far in the future, so we emit a `STOPPED_WATCHING` event. But there is another explanation which is that the order was already stored. So we were erroneously emitting `STOPPED_WATCHING` events for orders which we were still watching.
This PR fixes the problem by adding a third return value to `DB.AddOrders`: `alreadyStored` which contains the orders which weren’t added because they are already stored in the database.
> Don't emit STOPPED_WATCHING events for orders that were already stored

- packages/mesh-browser-lite/src/database.ts
When the database contains many orders, this optimization changes the worst-case performance of `GetOrderStatuses` from ~5-6s to ~100ms-1s. Let's keep this in mind as we look at future optimizations. Dexie performance seems to be highly impacted by the number of operations in each transaction.
This PR also changes the `TransactionMode` used for Dexie transactions. We now use `r!` (read only) instead of `rw!` (read and write) when possible. This change did not appear to have a large observable impact on performance, but it doesn't hurt and may prove advantageous in certain situation.
> Optimize GetOrderStatuses in browser by using getBulk

- CHANGELOG.md
- core/core.go
- core/ordersync/ordersync.go
- core/ordersync_subprotocols.go
- orderfilter/filter.go
- orderfilter/filter_js.go
- orderfilter/shared.go
> Fixed bug in ordersync that caused nodes to use the wrong orderfilter

- docs/deployment_with_telemetry.md
This PR simply cherry-picked the last commit from #885. That PR was based on `master`, which caused it's history to be very out of date.
> update deployment with telemetry doc with log opts

- core/ordersync/ordersync.go
> Fix bug when saving ordersync progress

- core/core.go
- ethereum/blockwatch/block_watcher.go
- ethereum/blockwatch/block_watcher_test.go
- zeroex/orderwatch/order_watcher_test.go
Credit to @albrow for finding the problem and identifying the fix.
> fix: Prevent blockwatcher from missing contract events on startup

- CHANGELOG.md
- ethereum/contract_addresses.go
- scenario/orderopts/orderopts.go
- zeroex/ordervalidator/order_validator.go
- zeroex/orderwatch/order_watcher.go
- zeroex/orderwatch/order_watcher_test.go
> feature: Reject taker addresses that are nonzero and not on the whitelist

- go.mod
- yarn.lock
Fixes: #849 (Thanks @z2trillion)
> Upgrade to go 1.15

- packages/mesh-webpack-example-lite/yarn.lock
This PR just rebases https://github.com/0xProject/0x-mesh/pull/757 off the development branch.
Bumps [acorn](https://github.com/acornjs/acorn) from 6.3.0 to 6.4.1.
- [Release notes](https://github.com/acornjs/acorn/releases)
- [Commits](https://github.com/acornjs/acorn/compare/6.3.0...6.4.1)
Signed-off-by: dependabot[bot] <support@github.com>
> Bump acorn from 6.3.0 to 6.4.1 in /packages/webpack-example-lite

- package.json
- packages/mesh-browser-lite/package.json
- packages/mesh-browser/package.json
- packages/mesh-graphql-client/package.json
- yarn.lock
I deleted the `yarn.lock` file and re-generated it by running `yarn`. Doing this naively broke the document generation step of our `cut-release` Makefile target, so I added a resolution that would prevent `yarn` from updating `typedoc-plugin-markdown` to `2.4` (this version appears to be incompatible with `@0x/ts-doc-gen`).
> Re-generated yarn.lock file

- dockerfiles/mesh-bootstrap/Dockerfile
- dockerfiles/mesh-bridge/Dockerfile
- dockerfiles/mesh/Dockerfile
> Upgraded Dockerfiles to go 1.15.2

- packages/mesh-graphql-client/src/types.ts
- zeroex/ordervalidator/order_validator.go
The "INVALID" order event end state pops up in Mesh rejected orders response, but the typescript enum doesn't handle it. This PR adds `INVALID` back to the typescript enum. 
https://github.com/0xProject/0x-mesh/blob/29a468866e7a750022d8b3d25c2947c5ed533385/zeroex/ordervalidator/order_validator.go#L186-L200
https://github.com/0xProject/0x-mesh/blob/development-v4/zeroex/order.go#L317
> Add back INVALID order event end state
