0xProject/0x-mesh

- core/core.go
- db/collection.go
- db/db.go
- db/errors.go
- meshdb/meshdb_test.go
- zeroex/orderwatch/watcher.go
Fixes #28.
I only added a few typed errors for now. It is probably not necessary to create a new error type for every possible error that might be returned, but if we need more in the future we can always add them.
> Improve db errors

- zeroex/order_validator.go
- zeroex/orderwatch/watcher.go
Addresses: https://github.com/0xProject/0x-mesh/issues/94
> orderwatch: Add TxHash to Order events emitted by OrderWatcher 

- core/message_handler.go
- meshdb/meshdb.go
Fixes https://github.com/0xProject/0x-mesh/issues/79
> Don't share orders that have already been marked as deleted

- cmd/mesh/main.go
- rpc/server.go
> Make all error logs use the "error" key

- core/message_handler.go
Since #107 and #83 have been merged, we can now optimize the `GetMessagesToShare` method.
Fixes #84.
> Optimize GetMessagesToShare using new db methods

- constants/constants.go
> constants: Add support for more testnets

- .circleci/config.yml
- Gopkg.lock
- Makefile
@fabio normally I would wait for your review but this PR is a hotfix to address the immediate issues with CI. Going to go ahead and merge.
> Update Makefile and disable Wasm tests on CI

- zeroex/order.go
Fixes: #108
And fixes some whitespace issues.
> zeroex: Implement custom JSON Marshal/Unmarshal methods for SignedOrder

- core/message_handler.go
Without snapshots, there was a slight chance that we would return the wrong number of orders if the db state changed in between our two queries.
> Use a snapshot for GetMessagesToShare

- core/core.go
- zeroex/orderwatch/expiration_watcher.go
- zeroex/orderwatch/expiration_watcher_test.go
- zeroex/orderwatch/order_watcher.go
Fixes: https://github.com/0xProject/0x-mesh/issues/93
> core/orderwatch: Add OrderExpirationBuffer config to Mesh

- core/core.go
> Segregate pubsub topic and rendezvous by Ethereum network id

- core/core.go
- core/validation.go
- zeroex/orderwatch/order_watcher.go
> zeroex/orderwatch: Validate order networkId & avoid sending entry order event payloads

- core/validation.go
Add a max order expiration check to our validation and set it to 30 days.
@weijiewu8 @albrow do you both agree with the 30 day expiration maximum?
> core: Check for max expiration of orders

- cmd/mesh/rpc_handler.go
> rpc: Fix `i/o timeout` error

- core/core.go
- ethereum/blockchain_lifecycle.go
- ethereum/eth_watcher.go
- ethereum/eth_watcher_test.go
> ethereum: Refactor EthWatcher

- constants/constants.go
- core/message_handler.go
- ethereum/blockchain_lifecycle.go
- ethereum/eth_watcher_test.go
- ethereum/sign.go
- ethereum/wrappers/coordinator_registry.go
- zeroex/order_validator.go
- zeroex/order_validator_test.go
> zeroex: Validate coordinator orders

- core/core.go
- ethereum/blockwatch/client.go
- Make block polling interval a config.
- Fix edge-case where block not found.
> blockwatch/core: Fix block not found, make polling interval configurable

- DOCUMENTATION.md
- README.md
> mesh: Add documentation markdown to repo

- db/global_transaction_test.go
- db/transaction_test.go
> Increase transaction exclusion test timeout

- package.json
- yarn.lock
> Update wrtc dependency for compatibility with Node 12

- cmd/mesh/rpc_handler.go
- core/core.go
- rpc/client.go
- rpc/client_server_test.go
- rpc/service.go
> rpc: Implement GetOrders RPC method

- Gopkg.lock
- Gopkg.toml
- cmd/mesh/rpc_handler.go
- core/core.go
- core/message_handler.go
- core/validation.go
- core/validation_test.go
- rpc/client_server_test.go
- rpc/service.go
- zeroex/order.go
> core/rpc/zeroex: Implement SignedOrder schema validation

- DEPLOYMENT.md
- DEVELOPMENT.md
- README.md
- USAGE.md
@fabioberger in this PR I split up documentation into:
- __DEPLOYMENT.md__ which includes instructions for deploying a 0x Mesh node.
- __USAGE.md__ which describes how to use the JSON-RPC API and lists all available methods.
- __DEVELOPMENT.md__ which helps external contributors get started with the 0x Mesh codebase.
I also made a lot of smaller changes to make sure the docs are up to date. Open to feedback about whether this is the best structure. What do you think?
> Re-organize and improve documentation

- cmd/mesh/rpc_handler.go
- core/core.go
- rpc/client.go
- rpc/client_server_test.go
- rpc/service.go
Identical to #198 just now merging into development.
> rpc: Implement GetOrders RPC method (round 2)

- DEPLOYMENT.md
- DEVELOPMENT.md
- README.md
- USAGE.md
- core/core.go
Fixes #222.
For now the version is just called "development". When we create the release branch in preparation for releasing version `1.0.0-beta`, we will manually update the version in these files. In the future, we can probably automate this so we don't have to change any files manually.
> Add version to all doc files and log it on initialization

- Makefile
- cmd/db-integrity-check/main.go
- db/integrity_check.go
- db/integrity_check_test.go
- db/operations.go
This tool can help us diagnose #227 by detecting potential problems with database integrity.
> Implement tool for checking database integrity

- cmd/mesh-bootstrap/main.go
- constants/constants.go
- p2p/bootstrap.go
- p2p/node.go
Fixes: #223 
This PR updates the bootstrap list to include our own dedicated bootstrap nodes.
> Update the bootstrap list and use it in mesh-bootstrap

- ethereum/contract_addresses.go
- examples/javascript_websocket_client/index.js
- examples/javascript_websocket_client/index.ts
Updates the V2 smart contract addresses to the patched versions.
> ethereum: update V2 0x contract addresses

- DEPLOYMENT.md
- core/core.go
- p2p/node_test.go
We are comfortable doing this now that we are running our own bootstrap nodes.
> Set USE_BOOTSTRAP_LIST to true by default

- DEPLOYMENT.md
- core/core.go
- p2p/node.go
As a side-effect this change makes `P2P_LISTEN_PORT` required.
> Introduce a temporary hack to discover public IP address

- DEPLOYMENT.md
- core/core.go
- p2p/node.go
> Revert "Introduce a temporary hack to discover public IP address"

- p2p/node.go
This PR sets up `libp2p.Routing` the same way as we were doing for our bootstrap nodes. I *think* the problem before was that our bootstrap nodes and non-bootstrap nodes were using different configurations for routing and that is why they could not properly discover the relay and AutoNAT services.
> Use our custom DHT protocol for routing in p2p/node.go

- core/message_handler.go
Previously, we were logging the `"received new valid order from peer"` message too early, before some validation steps had been completed. This PR fixes the issue by only logging the message when the order has passed _all_ validation. As a consequence of this bug, we were logging multiple times for orders which had already been stored, which can affect metrics such as "top order sharers".
> Don't fire log message for orders until all validation steps have passed

- core/core.go
- ethereum/blockwatch/block_watcher.go
- ethereum/blockwatch/block_watcher_test.go
> blockwatch: Use consistent asynchronous API

- core/core.go
- p2p/node.go
- p2p/node_test.go
- p2p/notifee.go
> p2p: Use consistent asynchronous API

- CHANGELOG.md
- cmd/cut-release/main.go
- docs/SUMMARY.md
This PR:
- Adds a CHANGELOG.md file to the repo
- Adds the version to the "Upcoming release" label during `cut-release`
- Adds CHANGELOG to doc site.
> cmd/docs: Add CHANGELOG.md

- docs/USAGE.md
> Update link in USAGE.md

- CHANGELOG.md
This PR updates the changelog to include all of my changes since version `3.0.1-beta`. @fabioberger mind going through and also adding any of your changes?
> Update changelog in preparation for version 4.0.0-beta

- core/core.go
This PR adds a new for loop which is started in a goroutine and logs stats every 5 minutes. This will helps us get a much better overview of the current state of the Mesh network and answer questions like:
- How many nodes have upgraded to the latest version?
- What is the average number of orders for each node?
- What is the average number of peers for each node?
And detect potential issues such as:
- A node is too many blocks behind on mainnet.
- A node is not connected to any peers.
> Periodically log stats

- CHANGELOG.md
- docs/rpc_api.md
This PR also fixes a small bug in the docs for the RPC API.
> Add missing CHANGELOG entries in preparation for version 5.1.0-beta

- .circleci/config.yml
- Makefile
- browser/ts/index.ts
> Run all TS linters in make lint and in CI

- Gopkg.lock
- cmd/mesh-bootstrap/main.go
- cmd/mesh-bootstrap/storage.go
- integration-tests/integration_test.go
- p2p/bootstrap.go
- p2p/opts.go
- p2p/opts_js.go
This PR is the same as https://github.com/0xProject/0x-mesh/pull/486 but rebased off of the `development` branch.
> Add SQL Datastore option to Bootstrap Node

- docs/deployment.md
Based on feedback on our Discord channel.
> Update deployment guide with options more suitable for production

- CHANGELOG.md
I forgot to push this commit as part of https://github.com/0xProject/0x-mesh/pull/514.
> Update CHANGELOG to include fix for TypeScript RPC client

- docs/deployment.md
These env vars have been outdated for quite a while.
> Fix outdated env vars in docs/deployment.md

- CHANGELOG.md
Forgot to include this in #539.
> Add memory leak fix to changelog

- CHANGELOG.md
Adds the missing changelog entry for #533.
> Add changelog entry for browser persistence

- CHANGELOG.md
- cmd/mesh/rpc_handler.go
- rpc/service.go
Same as #552 but for the `development` branch this time.
> Always unsubscribe from order events in SetupOrderStream

- db/transaction.go
- db/transaction_test.go
Fixes #565. 
The best we can do for now is catch this early and return a better error.
> db: Return an error when operating on the same model in a single transaction

- CHANGELOG.md
- cmd/mesh/rpc_handler.go
- core/core.go
- rpc/client.go
- rpc/client_server_test.go
- rpc/clients/typescript/src/types.ts
- rpc/clients/typescript/src/ws_client.ts
- rpc/clients/typescript/test/ws_client_test.ts
Fixes: https://github.com/0xProject/0x-mesh/issues/567
> rpc,core: Add timestamp to GetOrders snapshots

- issue_template.md
This will help us more effectively understand and respond to issues. This template is roughly based on https://embeddedartistry.com/blog/2017/08/18/a-github-issue-template-for-your-projects/.
> Create issue template

- CHANGELOG.md
- core/core.go
> core: Only wait for block to be processed if not sync'd to latest block already

- zeroex/orderwatch/order_watcher.go
- zeroex/orderwatch/order_watcher_test.go
> orderwatch: Add missing tests

- .circleci/config.yml
- browser/package.json
- browser/yarn.lock
- examples/browser/src/index.ts
- examples/browser/yarn.lock
- Updated order format for compatibility with 0x v3
- Upgraded to latest version of `@0x/utils` to fix an issue with `BigNumber`
- Added a new CI step to make sure the browser example builds
> Fix browser example and make sure it builds in CI

- CHANGELOG.md
- README.md
- browser/package.json
- core/core.go
- docs/browser/README.md
- docs/browser/reference.md
- docs/deployment.md
- docs/deployment_with_telemetry.md
- docs/json_rpc_clients/typescript/reference.md
- docs/rpc_api.md
- go.mod
- go.sum
- rpc/clients/typescript/package.json
This release contains cherry-picked commits from #650. It doesn't contain every change from the current `development` branch.
> Release version 8.1.1

- CHANGELOG.md
> De-duped bug fix from CHANGELOG.md

- CHANGELOG.md
> Add v8.2.0 CHANGELOG entry

- go.mod
- go.sum
> Update github.com/0xProject/sql-datastore dependency

- .circleci/config.yml
- CHANGELOG.md
- README.md
- browser/package.json
- core/core.go
- db/transaction.go
- db/transaction_test.go
- docs/browser/reference.md
- docs/deployment.md
- docs/deployment_with_telemetry.md
- docs/json_rpc_clients/typescript/reference.md
- docs/rpc_api.md
- ethereum/blockchain_lifecycle.go
- ethereum/contract_addresses.go
- rpc/clients/typescript/package.json
- rpc/clients/typescript/src/ws_client.ts
- zeroex/orderwatch/order_watcher.go
- zeroex/orderwatch/order_watcher_test.go
> Backport Release 7.1.0-beta (0x V2 Mesh)

- rpc/clients/typescript/test/ws_client_test.ts
Fix `onClose` test for TS RPC client so that we explicitly check for the `unsubscribe` payload instead of counting messages received, since that can differ based on the tests timing.
> rpc: Fix intermittent CI failure in TS RPC client test

- CONTRIBUTING.md
This PR adds some new instructions for developers in different OSes, in particular for Ubuntu. This PR also explicitly mentions some dependencies that we previously assumed developers already had installed.
> Improve Contributing Guide for Linux users

- zeroex/orderwatch/order_watcher.go
Currently, we are only allowing a single order validation request at a time. This is enforced by the mutex surrounding this operation. 
Upon closer inspection however, I realized that we can actually allow multiple order validations to occur, as long as they occur at the same block height. In order to accomplish this, we can use a read-write lock instead of a simple mutex. Go routines that wish to perform validation at the latest stored block height can acquire read mutexes that can co-exist, and whenever we wish to process new block events and increment the latest block height, we acquire a write mutex. The write mutex takes precedence over any new read mutex lock, and waits for all read mutexes to be released.
This should drastically improve the speed with which orders are added to Mesh …
> orderwatch: Allow parallel re-validation requests at the same block height

- test-wasm/go_js_wasm_exec
Deletes some dead code in go_js_wasm_exec.
> Delete dead code in go_js_wasm_exec

- cmd/peer-id-to-pub-key/REAMDE.md
- cmd/peer-id-to-pub-key/main.go
- go.mod
> Add CLI for extracting public key from peer ID

- .drone.yml
- CHANGELOG.md
- README.md
- RELEASE_CHANGELOG.md
- browser/package.json
- core/core.go
- docs/browser/reference.md
- docs/deployment.md
- docs/deployment_with_telemetry.md
- docs/json_rpc_clients/typescript/reference.md
- docs/rpc_api.md
- meshdb/meshdb.go
- meshdb/meshdb_test.go
- p2p/opts_js.go
- rpc/clients/typescript/package.json
- zeroex/orderwatch/order_watcher.go
- zeroex/orderwatch/order_watcher_test.go
> Release version 9.0.1

- db/open_js.go
> Fix typo in log about BrowserFS

- packages/browser-lite/src/index.ts
> Promisified the `@0x/mesh-browser-lite` API

- docs/browser.md
- docs/rpc_api.md
> Fix some links in the docs

- packages/rpc-client/yarn.lock
This PR cherry picks the fix from https://github.com/0xProject/0x-mesh/pull/751.
> Bump handlebars from 4.1.2 to 4.7.3 in /packages/rpc-client

- CHANGELOG.md
- core/ordersync_subprotocols.go
> Duplicate PR of the fix to ordersync

- .circleci/config.yml
- constants/constants.go
- ethereum/contract_addresses.go
> Update ganache addresses

- docs/custom_order_filters.md
- docs/summary.md
> Add custom order filters documentation

- p2p/node_test.go
Hopefully will fix occasional CI failures (e.g. see https://app.circleci.com/pipelines/github/0xProject/0x-mesh/2895/workflows/a903ff99-2703-4a24-8c13-83aa9afd7859/jobs/3053).
> Increase sleep duration in TestPingPong

- CHANGELOG.md
> Update Changelog for PR #809

- go.mod
- go.sum
> Updated logrus dependency

- cmd/cut-release/main.go
> Add prettier step to `make cut-release`

- packages/rpc-client/src/ws_client.ts
> Fixed small bug in the ws rpc client

- .drone.yml
This PR adds the new `.drone.yml` configuration for new runner.
> fix: update drone configuration

- CHANGELOG.md
- README.md
- RELEASE_CHANGELOG.md
- core/core.go
- core/ordersync/ordersync.go
- core/ordersync_subprotocols.go
- docs/browser-bindings/browser-lite/README.md
- docs/browser-bindings/browser-lite/reference.md
- docs/browser-bindings/browser/README.md
- docs/browser-bindings/browser/reference.md
- docs/deployment.md
- docs/deployment_with_telemetry.md
- docs/json_rpc_clients/typescript/README.md
- docs/json_rpc_clients/typescript/reference.md
- docs/rpc_api.md
- orderfilter/filter.go
- orderfilter/filter_js.go
- orderfilter/shared.go
- packages/browser-lite/package.json
- packages/browser/package.json
- packages/rpc-client/package.json
> Release 9.4.1

- core/core.go
- ethereum/blockwatch/block_watcher.go
- ethereum/blockwatch/block_watcher_test.go
- ethereum/blockwatch/client.go
- ethereum/blockwatch/fake_client.go
- ethereum/blockwatch/fake_log_client.go
- zeroex/orderwatch/order_watcher_test.go
> Added context as a parameter in `ethereum/blockwatch.Client`

- .circleci/config.yml
- CHANGELOG.md
- CONTRIBUTING.md
- dockerfiles/mesh-bootstrap/Dockerfile
- dockerfiles/mesh-bridge/Dockerfile
- dockerfiles/mesh/Dockerfile
> Updated some out of date references of Go 1.14 to Go 1.15

- CHANGELOG.md
> Added missing entries to the changelog

- integration-tests/graphql_integration_test.go
- packages/mesh-graphql-client/test/graphql_client_test.ts
> Updated an integration test to be version agnostic

- CHANGELOG.md
> Updated changelog for configurable order validation

- .circleci/config.yml
- CONTRIBUTING.md
- ethereum/contract_addresses.go
- go.mod
- go.sum
- zeroex/order.go
- zeroex/order_v4.go
- zeroex/order_v4_test.go
- zeroex/utis.go
> Add OrderV4 struct with hashes and signatures

- scenario/scenario.go
- scenario/scenario_v4.go
- zeroex/order_v4.go
- zeroex/order_v4_test.go
- zeroex/ordervalidator/order_validator_v4.go
- zeroex/ordervalidator/order_validator_v4_test.go
- zeroex/orderwatch/order_watcher_test.go
> Order validator part II

- .circleci/config.yml
- CONTRIBUTING.md
- zeroex/order_v4.go
- zeroex/order_v4_test.go
> Update ganache snapshot

- packages/mesh-browser-lite/package.json
- packages/mesh-graphql-client/package.json
- packages/mesh-graphql-client/src/index.ts
- packages/mesh-graphql-client/src/queries.ts
- packages/mesh-integration-tests/package.json
- yarn.lock
> ADDS random client fixes

- graphql/generated/generated.go
- graphql/schema.graphql
- packages/mesh-graphql-client/src/types.ts
- packages/mesh-graphql-client/test/graphql_client_test.ts
> Order event order fields are optional

- README.md
- core/core.go
- docs/browser-bindings/browser-lite/README.md
- docs/browser-bindings/browser-lite/reference.md
- docs/browser-bindings/browser/README.md
- docs/browser-bindings/browser/reference.md
- docs/deployment.md
- docs/deployment_with_telemetry.md
- docs/graphql-client/README.md
- docs/graphql-client/reference.md
- docs/graphql_api.md
- packages/mesh-browser-lite/package.json
- packages/mesh-browser-shim/package.json
- packages/mesh-browser/package.json
- packages/mesh-graphql-client/package.json
- packages/mesh-integration-tests/package.json
- packages/mesh-webpack-example-lite/package.json
- packages/mesh-webpack-example/package.json
Fix the bug where graphql client crashes when takerAddress is invalid.
> Release version 10.2.1

- packages/mesh-graphql-client/src/index.ts
- packages/mesh-graphql-client/src/queries.ts
- packages/mesh-graphql-client/src/types.ts
Fixes some minor query result format issues for v4.
> fix: graphql client V4 order query response structure

- db/sql_implementation.go
- zeroex/orderwatch/order_watcher.go
> fix: remove poor performing query from AddOrders

- README.md
- core/core.go
- db/sql_implementation.go
- docs/browser-bindings/browser-lite/README.md
- docs/browser-bindings/browser-lite/reference.md
- docs/browser-bindings/browser/README.md
- docs/browser-bindings/browser/reference.md
- docs/deployment.md
- docs/deployment_with_telemetry.md
- docs/graphql-client/README.md
- docs/graphql-client/reference.md
- docs/graphql_api.md
- packages/mesh-browser-lite/package.json
- packages/mesh-browser-shim/package.json
- packages/mesh-browser/package.json
- packages/mesh-graphql-client/package.json
- packages/mesh-integration-tests/package.json
- packages/mesh-webpack-example-lite/package.json
- packages/mesh-webpack-example/package.json
- zeroex/orderwatch/order_watcher.go
> release: 10.2.2

- README.md
- core/core.go
- docs/browser-bindings/browser-lite/README.md
- docs/browser-bindings/browser-lite/reference.md
- docs/browser-bindings/browser/README.md
- docs/browser-bindings/browser/reference.md
- docs/deployment.md
- docs/deployment_with_telemetry.md
- docs/json_rpc_clients/typescript/README.md
- docs/json_rpc_clients/typescript/reference.md
- docs/rpc_api.md
- p2p/node.go
- p2p/opts.go
- packages/browser-lite/package.json
- packages/browser/package.json
- packages/rpc-client/package.json
- add an optional configuration for custom public ip sources
- update docs
> add multiple external sources to grab public IP by mesh

- README.md
- core/core.go
- docs/browser-bindings/browser-lite/README.md
- docs/browser-bindings/browser-lite/reference.md
- docs/browser-bindings/browser/README.md
- docs/browser-bindings/browser/reference.md
- docs/deployment.md
- docs/deployment_with_telemetry.md
- docs/graphql-client/README.md
- docs/graphql-client/reference.md
- docs/graphql_api.md
- p2p/node.go
- p2p/opts.go
- packages/mesh-browser-lite/package.json
- packages/mesh-browser-shim/package.json
- packages/mesh-browser/package.json
- packages/mesh-graphql-client/package.json
- packages/mesh-integration-tests/package.json
- packages/mesh-webpack-example-lite/package.json
- packages/mesh-webpack-example/package.json
- zeroex/orderwatch/order_watcher.go
Includes a patch to fix our `getPublicIP`
> release: 11.0.3
